[package]
name = "feagi-basis-threading"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "Various threading related structures used through FEAGI"

[dependencies]
