[package]
name = "feagi-basis-threading"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "Various threading related structures used through FEAGI"

[features]

std = [
    "alloc",
    "serde/std", "thingbuf/std", "thiserror/std"
]

alloc = [
    "serde/alloc", "heapless/alloc", "thingbuf/alloc",
]

[dependencies]

# External Crates
serde = {workspace = true}
heapless = {workspace = true, default-features = false, features = ["serde"]}
thiserror = {workspace = true}
thingbuf = {workspace = true}
