[package]
name = "feagi-genomic"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true

[features]

default = [
    "std",
    "genomic-data"
]

# ========================= Toggleable Features ========================= #
# Features that add certain libraries/crates that extend the functionality
# and performance of the FEAGI application
# In order of Directly activated crates, other features here, external crate features, feagi crate features

std = [
    "alloc",
]

alloc = [

]

genomic-data = [
    "feagi-genomic-data"
]

[dependencies]
feagi-genomic-context = {path = "feagi-genomic-context"}
feagi-genomic-data = {path = "feagi-genomic-data", optional = true}

[lints]
workspace = true
