[package]
name = "feagi-genomic"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true

[dependencies]
feagi-genomic-context = {path = "feagi-genomic-context"}
feagi-genomic-data = {path = "feagi-genomic-data"}

[lints]
workspace = true
