use crate::values::quantizable::{
    QuantizedSignedIntegerTrait, QuantizedSignedIntegerUnwrappedTrait, SignedIntegerQuantizationLevel,
};
use crate::values::spatial::feagi_data_values_spatial_error::FeagiDataValuesSpatialError;

#[derive(Debug, Clone, Copy, Hash, PartialEq, Eq)]
pub struct SignedIntegerSpatial<Q: QuantizedSignedIntegerTrait, const NUM_DIMS: usize> {
    data: [Q; NUM_DIMS],
}

impl<Q: QuantizedSignedIntegerTrait, const NUM_DIMS: usize> serde::Serialize for SignedIntegerSpatial<Q, NUM_DIMS> {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        self.data.as_slice().serialize(serializer)
    }
}

impl<'de, Q: QuantizedSignedIntegerTrait, const NUM_DIMS: usize> serde::Deserialize<'de> for SignedIntegerSpatial<Q, NUM_DIMS>
where
    Q: serde::Deserialize<'de>,
{
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let values = Vec::<Q>::deserialize(deserializer)?;
        if values.len() != NUM_DIMS {
            return Err(serde::de::Error::custom(format!(
                "expected {} spatial elements, got {}",
                NUM_DIMS,
                values.len()
            )));
        }
        let data: [Q; NUM_DIMS] = values
            .try_into()
            .map_err(|_| serde::de::Error::custom("failed converting spatial elements to fixed-size array"))?;
        Ok(Self { data })
    }
}

/// Shared signed-integer spatial semantics for both raw and wrapped values.
pub trait SignedIntegerSpatialTrait<Q: QuantizedSignedIntegerTrait, const NUM_DIMS: usize>:
    Copy
    + Clone
    + Send
    + Sync
    + core::fmt::Debug
    + core::cmp::PartialEq
    + core::cmp::Eq
    + core::hash::Hash
    + Sized
    + 'static
{
    /// Number of spatial axes represented by this value.
    const NUM_DIMS: usize = NUM_DIMS;

    /// What quantization level this represents.
    const LEVEL: SignedIntegerQuantizationLevel = Q::LEVEL;

    /// Spatial of all elements as one.
    const QUANT_ONES: Self;

    /// Get a flat slice view of axis values.
    fn as_slice(&self) -> &[Q];

    /// Create from a correctly sized array.
    fn new_from_array(array: [Q; NUM_DIMS]) -> Self;

    /// Create from a correctly sized array of some other quant. Does NOT validate bounds.
    fn new_from_quant_unchecked<FromQuant: QuantizedSignedIntegerTrait>(
        value: SignedIntegerSpatial<FromQuant, NUM_DIMS>,
    ) -> Self;

    /// Create from a correctly sized array of some other quant, returning an error if any axis
    /// value does not fit in the current quantization.
    fn new_from_quant<FromQuant: QuantizedSignedIntegerTrait>(
        value: SignedIntegerSpatial<FromQuant, NUM_DIMS>,
    ) -> Result<Self, FeagiDataValuesSpatialError>;

    /// Create from a correctly sized array of some other quant, clamping each axis value to fit.
    fn new_from_quant_clamped<FromQuant: QuantizedSignedIntegerTrait>(
        value: SignedIntegerSpatial<FromQuant, NUM_DIMS>,
    ) -> Self;

    /// Clamps each axis value for another quantization, but does not change the quantization
    /// itself.
    fn clamp_for_quantization<ClampFor: QuantizedSignedIntegerTrait>(self) -> Self;

    /// Clamps each axis value for a runtime-provided quantization level, but does not change the
    /// quantization itself.
    fn clamp_for_quantization_level_runtime(self, level: SignedIntegerQuantizationLevel) -> Self;
}

/// Marker trait for raw [`SignedIntegerSpatial`] values.
pub trait SignedIntegerSpatialUnwrappedTrait<Q: QuantizedSignedIntegerTrait, const NUM_DIMS: usize>:
    SignedIntegerSpatialTrait<Q, NUM_DIMS>
{
}

/// Shared behaviour implemented by every strongly-typed wrapper generated by
/// [`create_wrapped_signed_integer_spatial`].
pub trait SignedIntegerSpatialWrappedTrait<Q: QuantizedSignedIntegerTrait, const NUM_DIMS: usize>:
    SignedIntegerSpatialTrait<Q, NUM_DIMS>
    + From<SignedIntegerSpatial<Q, NUM_DIMS>>
    + AsRef<SignedIntegerSpatial<Q, NUM_DIMS>>
{
    /// The underlying unwrapped spatial value this wrapper stores.
    type Spatial: SignedIntegerSpatialUnwrappedTrait<Q, NUM_DIMS>;

    /// Spatial of all elements as zero.
    const QUANT_ZEROS: Self;

    /// Create from an unwrapped spatial without checking any validity.
    fn wrap_unchecked(value: SignedIntegerSpatial<Q, NUM_DIMS>) -> Self;

    /// Removes the wrapper.
    fn dewrap(self) -> SignedIntegerSpatial<Q, NUM_DIMS>;

    /// Wrap an unwrapped spatial.
    fn wrap(value: SignedIntegerSpatial<Q, NUM_DIMS>) -> Self {
        Self::wrap_unchecked(value)
    }
}

impl<Q: QuantizedSignedIntegerTrait, const NUM_DIMS: usize> SignedIntegerSpatial<Q, NUM_DIMS> {
    /// What quantization level this represents
    pub const LEVEL: SignedIntegerQuantizationLevel = Q::LEVEL;

    /// Spatial of all elements as zero
    pub const QUANT_ZEROS: SignedIntegerSpatial<Q, NUM_DIMS> = Self::new_from_array_const([Q::QUANT_ZERO; NUM_DIMS]);

    /// Spatial of all elements as one
    pub const QUANT_ONES: SignedIntegerSpatial<Q, NUM_DIMS> = Self::new_from_array_const([Q::QUANT_ONE; NUM_DIMS]);

    /// Create self from a correctly sized array in const context
    pub const fn new_from_array_const(array: [Q; NUM_DIMS]) -> Self {
        Self { data: array }
    }

    /// Create self from a correctly sized array
    pub fn new_from_array(array: [Q; NUM_DIMS]) -> Self {
        Self { data: array }
    }

    /// Create self from a correctly sized isize array. Does NOT validate quantization bounds!
    pub fn new_from_isize_array_unchecked(isize_array: [isize; NUM_DIMS]) -> Self {
        let mut data = [Q::QUANT_ZERO; NUM_DIMS];
        data.iter_mut()
            .zip(isize_array.iter())
            .for_each(|(q, i)| *q = Q::quant_from_isize_unchecked(*i));
        Self { data }
    }

    /// Create self from a correctly sized isize array, returning an error if any axis value does
    /// not fit in the current quantization.
    pub fn new_from_isize_array(isize_array: [isize; NUM_DIMS]) -> Result<Self, FeagiDataValuesSpatialError> {
        let mut data = [Q::QUANT_ZERO; NUM_DIMS];
        for (q, &i) in data.iter_mut().zip(isize_array.iter()) {
            *q = Q::quant_try_from_isize(i).map_err(|e| e.into())?;
        }
        Ok(Self { data })
    }

    /// Create self from a correctly sized array of some other quant. Does NOT validate bounds!
    pub fn new_from_quant_unchecked<FromQuant: QuantizedSignedIntegerTrait>(value_array: SignedIntegerSpatial<FromQuant, NUM_DIMS>) -> Self {
        let mut data = [Q::QUANT_ZERO; NUM_DIMS];
        data.iter_mut()
            .zip(value_array.as_data_slice().iter())
            .for_each(|(q, &v)| *q = Q::from_quantization_unchecked(v));
        Self { data }
    }

    /// Create self from a correctly sized array of some other quant, returning an error if any
    /// axis value does not fit in the current quantization.
    pub fn new_from_quant<FromQuant: QuantizedSignedIntegerTrait>(
        value_array: SignedIntegerSpatial<FromQuant, NUM_DIMS>,
    ) -> Result<Self, FeagiDataValuesSpatialError> {
        let mut data = [Q::QUANT_ZERO; NUM_DIMS];
        for (q, &v) in data.iter_mut().zip(value_array.as_data_slice().iter()) {
            *q = Q::try_from_quantization(v).map_err(|e| e.into())?;
        }
        Ok(Self { data })
    }

    /// Create self from a correctly sized array of some other quant, clamping each axis value to
    /// fit in the current quantization.
    pub fn new_from_quant_clamped<FromQuant: QuantizedSignedIntegerTrait>(value_array: SignedIntegerSpatial<FromQuant, NUM_DIMS>) -> Self {
        let mut data = [Q::QUANT_ZERO; NUM_DIMS];
        data.iter_mut()
            .zip(value_array.as_data_slice().iter())
            .for_each(|(q, &v)| *q = Q::from_quantization_clamped(v));
        Self { data }
    }

    /// Converts this value from its current quantization to another quantization without checking if valid.
    pub fn to_quantization_unchecked<ToQuant: QuantizedSignedIntegerTrait>(self) -> SignedIntegerSpatial<ToQuant, NUM_DIMS> {
        let mut out = [ToQuant::QUANT_ZERO; NUM_DIMS];
        out.iter_mut()
            .zip(self.data.iter())
            .for_each(|(o, &s)| *o = ToQuant::from_quantization_unchecked(s));
        SignedIntegerSpatial { data: out }
    }

    /// Tries to convert this value from its current quantization to another quantization,
    /// returning an error if any axis value does not fit.
    pub fn try_to_quantization<ToQuant: QuantizedSignedIntegerTrait>(
        self,
    ) -> Result<SignedIntegerSpatial<ToQuant, NUM_DIMS>, FeagiDataValuesSpatialError> {
        let mut out = [ToQuant::QUANT_ZERO; NUM_DIMS];
        for (o, &s) in out.iter_mut().zip(self.data.iter()) {
            *o = s.try_to_quantization().map_err(|e| e.into())?;
        }
        Ok(SignedIntegerSpatial { data: out })
    }

    /// Converts this value from its current quantization to another quantization, clamping each
    /// axis value to fit.
    pub fn to_quantization_clamped<ToQuant: QuantizedSignedIntegerTrait>(self) -> SignedIntegerSpatial<ToQuant, NUM_DIMS> {
        let mut out = [ToQuant::QUANT_ZERO; NUM_DIMS];
        out.iter_mut().zip(self.data.iter()).for_each(|(o, &s)| *o = s.to_quantization_clamped());
        SignedIntegerSpatial { data: out }
    }

    /// Clamps each axis value for another quantization, but does not change the quantization itself.
    pub fn clamp_for_quantization<ClampFor: QuantizedSignedIntegerTrait>(self) -> Self {
        let mut data = self.data;
        data.iter_mut().for_each(|q| *q = q.clamp_for_quantization::<ClampFor>());
        Self { data }
    }

    /// Clamps each axis value for a runtime-provided quantization level, but does not change the
    /// quantization itself.
    pub fn clamp_for_quantization_level_runtime(self, level: SignedIntegerQuantizationLevel) -> Self {
        let mut data = self.data;
        data.iter_mut().for_each(|q| *q = q.clamp_for_quantization_level_runtime(level));
        Self { data }
    }

    /// Output to a [`SignedIntegerSpatialEnum`] to abstract away quantization.
    pub fn to_enum(self) -> SignedIntegerSpatialEnum<NUM_DIMS> {
        match Q::LEVEL {
            SignedIntegerQuantizationLevel::I8 => SignedIntegerSpatialEnum::I8(self.to_quantization_unchecked()),
            SignedIntegerQuantizationLevel::I16 => SignedIntegerSpatialEnum::I16(self.to_quantization_unchecked()),
            SignedIntegerQuantizationLevel::I32 => SignedIntegerSpatialEnum::I32(self.to_quantization_unchecked()),
            SignedIntegerQuantizationLevel::I64 => SignedIntegerSpatialEnum::I64(self.to_quantization_unchecked()),
        }
    }

    /// Get as a fixed-size array
    pub fn as_data_slice(&self) -> &[Q; NUM_DIMS] {
        &self.data
    }

    /// Get as a mutable fixed-size array
    pub fn as_data_slice_mut(&mut self) -> &mut [Q; NUM_DIMS] {
        &mut self.data
    }

    /// Get as a flat slice view of axis values
    pub fn as_slice(&self) -> &[Q] {
        self.data.as_slice()
    }

    /// Get as a mutable flat slice view of axis values
    pub fn as_slice_mut(&mut self) -> &mut [Q] {
        self.data.as_mut_slice()
    }

    /// Returns spatial data with all elements zero
    pub fn new_zero() -> Self {
        Self::QUANT_ZEROS
    }
}

impl<Q: QuantizedSignedIntegerTrait, const NUM_DIMS: usize> SignedIntegerSpatialTrait<Q, NUM_DIMS>
    for SignedIntegerSpatial<Q, NUM_DIMS>
{
    const QUANT_ONES: Self = Self::new_from_array_const([Q::QUANT_ONE; NUM_DIMS]);

    fn as_slice(&self) -> &[Q] {
        self.data.as_slice()
    }

    fn new_from_array(array: [Q; NUM_DIMS]) -> Self {
        Self { data: array }
    }

    fn new_from_quant_unchecked<FromQuant: QuantizedSignedIntegerTrait>(
        value: SignedIntegerSpatial<FromQuant, NUM_DIMS>,
    ) -> Self {
        let mut data = [Q::QUANT_ZERO; NUM_DIMS];
        data.iter_mut()
            .zip(value.as_data_slice().iter())
            .for_each(|(q, &v)| *q = Q::from_quantization_unchecked(v));
        Self { data }
    }

    fn new_from_quant<FromQuant: QuantizedSignedIntegerTrait>(
        value: SignedIntegerSpatial<FromQuant, NUM_DIMS>,
    ) -> Result<Self, FeagiDataValuesSpatialError> {
        let mut data = [Q::QUANT_ZERO; NUM_DIMS];
        for (q, &v) in data.iter_mut().zip(value.as_data_slice().iter()) {
            *q = Q::try_from_quantization(v).map_err(|e| e.into())?;
        }
        Ok(Self { data })
    }

    fn new_from_quant_clamped<FromQuant: QuantizedSignedIntegerTrait>(
        value: SignedIntegerSpatial<FromQuant, NUM_DIMS>,
    ) -> Self {
        let mut data = [Q::QUANT_ZERO; NUM_DIMS];
        data.iter_mut()
            .zip(value.as_data_slice().iter())
            .for_each(|(q, &v)| *q = Q::from_quantization_clamped(v));
        Self { data }
    }

    fn clamp_for_quantization<ClampFor: QuantizedSignedIntegerTrait>(self) -> Self {
        let mut data = self.data;
        data.iter_mut().for_each(|q| *q = q.clamp_for_quantization::<ClampFor>());
        Self { data }
    }

    fn clamp_for_quantization_level_runtime(self, level: SignedIntegerQuantizationLevel) -> Self {
        let mut data = self.data;
        data.iter_mut().for_each(|q| *q = q.clamp_for_quantization_level_runtime(level));
        Self { data }
    }
}

impl<Q: QuantizedSignedIntegerTrait, const NUM_DIMS: usize> SignedIntegerSpatialUnwrappedTrait<Q, NUM_DIMS>
    for SignedIntegerSpatial<Q, NUM_DIMS>
{
}

/// Stores [`SignedIntegerSpatial`] as an enum to erase the generic type and to make transport easier.
///
/// NOTE that due to how enums work in Rust, memory allocation will always be at i64 quant levels!
#[derive(Debug, Clone, Copy, Hash, PartialEq, Eq, ::serde::Serialize, ::serde::Deserialize)]
pub enum SignedIntegerSpatialEnum<const NUM_DIMS: usize> {
    I8(SignedIntegerSpatial<i8, NUM_DIMS>),
    I16(SignedIntegerSpatial<i16, NUM_DIMS>),
    I32(SignedIntegerSpatial<i32, NUM_DIMS>),
    I64(SignedIntegerSpatial<i64, NUM_DIMS>),
}

impl<const NUM_DIMS: usize> SignedIntegerSpatialEnum<NUM_DIMS> {
    /// Get what level of quantization is contained
    pub fn get_level(&self) -> SignedIntegerQuantizationLevel {
        match self {
            Self::I8(_) => SignedIntegerQuantizationLevel::I8,
            Self::I16(_) => SignedIntegerQuantizationLevel::I16,
            Self::I32(_) => SignedIntegerQuantizationLevel::I32,
            Self::I64(_) => SignedIntegerQuantizationLevel::I64,
        }
    }

    /// Tries to convert to a spatial value of another quantization, returning an error if any axis
    /// value does not fit.
    pub fn try_into_quant<Quant: QuantizedSignedIntegerTrait>(
        self,
    ) -> Result<SignedIntegerSpatial<Quant, NUM_DIMS>, FeagiDataValuesSpatialError> {
        match self {
            Self::I8(value) => value.try_to_quantization(),
            Self::I16(value) => value.try_to_quantization(),
            Self::I32(value) => value.try_to_quantization(),
            Self::I64(value) => value.try_to_quantization(),
        }
    }

    /// Converts to a spatial value of another quantization without checking if valid.
    pub fn into_quant<Quant: QuantizedSignedIntegerTrait>(self) -> SignedIntegerSpatial<Quant, NUM_DIMS> {
        match self {
            Self::I8(value) => value.to_quantization_unchecked(),
            Self::I16(value) => value.to_quantization_unchecked(),
            Self::I32(value) => value.to_quantization_unchecked(),
            Self::I64(value) => value.to_quantization_unchecked(),
        }
    }

    /// Converts to a spatial value of another quantization, clamping each axis value to fit.
    pub fn into_quantization_clamped<Quant: QuantizedSignedIntegerTrait>(self) -> SignedIntegerSpatial<Quant, NUM_DIMS> {
        match self {
            Self::I8(value) => value.to_quantization_clamped(),
            Self::I16(value) => value.to_quantization_clamped(),
            Self::I32(value) => value.to_quantization_clamped(),
            Self::I64(value) => value.to_quantization_clamped(),
        }
    }
}

/// Shared behaviour for enums that hide the quantization generic of wrapped spatial values.
pub trait WrappedSignedIntegerSpatialEnum:
    Copy + Clone + Send + Sync + core::fmt::Debug + core::cmp::PartialEq + core::cmp::Eq + core::hash::Hash + Sized + 'static
{
    const NUM_DIMS: usize;
    type Shape<Q: QuantizedSignedIntegerUnwrappedTrait>;

    fn get_level(&self) -> SignedIntegerQuantizationLevel;

    fn new_from_quantized<FromQ: QuantizedSignedIntegerUnwrappedTrait>(value: Self::Shape<FromQ>) -> Self;

    fn into_quantization_unchecked<NewQ: QuantizedSignedIntegerUnwrappedTrait>(self) -> Self::Shape<NewQ>;

    fn try_into_quantization<NewQ: QuantizedSignedIntegerUnwrappedTrait>(self) -> Result<Self::Shape<NewQ>, FeagiDataValuesSpatialError>;

    fn into_quantization_clamped<NewQ: QuantizedSignedIntegerUnwrappedTrait>(self) -> Self::Shape<NewQ>;
}

/// Creates a wrapper for spatial signed-integer values.
#[macro_export]
macro_rules! create_wrapped_signed_integer_spatial {
    (
        $(#[$meta:meta])*
        $vis:vis $struct_name:ident,
        $num_dimensions:expr,
        $( ($index:tt, $field:ident, $wrapped_axis:ident) ),+ $(,)?
    ) => {
        $(#[$meta])*
        #[repr(transparent)]
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, ::serde::Serialize, ::serde::Deserialize)]
        $vis struct $struct_name<Q: $crate::values::quantizable::QuantizedSignedIntegerUnwrappedTrait>(
            $crate::values::spatial::integer_signed::SignedIntegerSpatial<Q, $num_dimensions>
        );

        ::paste::paste! {
            impl<Q: $crate::values::quantizable::QuantizedSignedIntegerUnwrappedTrait> $struct_name<Q> {
                pub const NUM_DIMS: usize = $num_dimensions;

                pub const fn const_new(
                    value: $crate::values::spatial::integer_signed::SignedIntegerSpatial<Q, $num_dimensions>
                ) -> Self {
                    Self(value)
                }

                pub fn new($( $field: $wrapped_axis<Q> ),+ ) -> Self {
                    Self(
                        $crate::values::spatial::integer_signed::SignedIntegerSpatial::new_from_array([
                            $( *$field.as_ref() ),+
                        ])
                    )
                }

                pub fn try_new_from_isizes($( $field: isize ),+ ) -> Result<Self, $crate::values::spatial::feagi_data_values_spatial_error::FeagiDataValuesSpatialError> {
                    Ok(Self(
                        $crate::values::spatial::integer_signed::SignedIntegerSpatial::new_from_isize_array([
                            $( $field ),+
                        ])?,
                    ))
                }

                pub fn new_from_isizes_unchecked($( $field: isize ),+ ) -> Self {
                    Self(
                        $crate::values::spatial::integer_signed::SignedIntegerSpatial::new_from_isize_array_unchecked([
                            $( $field ),+
                        ])
                    )
                }

                pub fn new_from_spatial(
                    value: $crate::values::spatial::integer_signed::SignedIntegerSpatial<Q, $num_dimensions>
                ) -> Self {
                    Self(value)
                }

                pub fn dewrap(
                    self
                ) -> $crate::values::spatial::integer_signed::SignedIntegerSpatial<Q, $num_dimensions> {
                    self.0
                }

                pub fn as_spatial(&self) -> &$crate::values::spatial::integer_signed::SignedIntegerSpatial<Q, $num_dimensions> {
                    &self.0
                }

                pub fn as_slice(&self) -> &[Q] {
                    self.0.as_slice()
                }

                pub fn new_from_array(array: [Q; $num_dimensions]) -> Self {
                    <Self as $crate::values::spatial::integer_signed::SignedIntegerSpatialTrait<Q, $num_dimensions>>::new_from_array(array)
                }

                pub fn to_quantization_unchecked<NewQ: $crate::values::quantizable::QuantizedSignedIntegerUnwrappedTrait>(self) -> $struct_name<NewQ> {
                    $struct_name::new_from_spatial(self.0.to_quantization_unchecked())
                }

                pub fn try_to_quantization<NewQ: $crate::values::quantizable::QuantizedSignedIntegerUnwrappedTrait>(
                    self
                ) -> Result<$struct_name<NewQ>, $crate::values::spatial::feagi_data_values_spatial_error::FeagiDataValuesSpatialError> {
                    Ok($struct_name::new_from_spatial(self.0.try_to_quantization()?))
                }

                pub fn to_quantization_clamped<NewQ: $crate::values::quantizable::QuantizedSignedIntegerUnwrappedTrait>(self) -> $struct_name<NewQ> {
                    $struct_name::new_from_spatial(self.0.to_quantization_clamped())
                }

                $(
                    pub fn [<get_ $field>](&self) -> &$wrapped_axis<Q> {
                        (&self.0.as_slice()[$index]).into()
                    }

                    pub fn [<get_ $field _mut>](&mut self) -> &mut $wrapped_axis<Q> {
                        (&mut self.0.as_slice_mut()[$index]).into()
                    }
                )+
            }

            impl<Q: $crate::values::quantizable::QuantizedSignedIntegerUnwrappedTrait>
                $crate::values::spatial::integer_signed::SignedIntegerSpatialTrait<Q, $num_dimensions> for $struct_name<Q>
            {
                const QUANT_ONES: Self = Self::const_new(
                    $crate::values::spatial::integer_signed::SignedIntegerSpatial::<Q, $num_dimensions>::QUANT_ONES,
                );

                fn as_slice(&self) -> &[Q] {
                    self.0.as_slice()
                }

                fn new_from_array(array: [Q; $num_dimensions]) -> Self {
                    <Self as $crate::values::spatial::integer_signed::SignedIntegerSpatialWrappedTrait<Q, $num_dimensions>>::wrap_unchecked(
                        $crate::values::spatial::integer_signed::SignedIntegerSpatial::new_from_array(array),
                    )
                }

                fn new_from_quant_unchecked<FromQuant: $crate::values::quantizable::QuantizedSignedIntegerTrait>(
                    value: $crate::values::spatial::integer_signed::SignedIntegerSpatial<FromQuant, $num_dimensions>,
                ) -> Self {
                    <Self as $crate::values::spatial::integer_signed::SignedIntegerSpatialWrappedTrait<Q, $num_dimensions>>::wrap_unchecked(
                        $crate::values::spatial::integer_signed::SignedIntegerSpatial::<Q, $num_dimensions>::new_from_quant_unchecked(value),
                    )
                }

                fn new_from_quant<FromQuant: $crate::values::quantizable::QuantizedSignedIntegerTrait>(
                    value: $crate::values::spatial::integer_signed::SignedIntegerSpatial<FromQuant, $num_dimensions>,
                ) -> Result<Self, $crate::values::spatial::feagi_data_values_spatial_error::FeagiDataValuesSpatialError> {
                    Ok(<Self as $crate::values::spatial::integer_signed::SignedIntegerSpatialWrappedTrait<Q, $num_dimensions>>::wrap_unchecked(
                        $crate::values::spatial::integer_signed::SignedIntegerSpatial::<Q, $num_dimensions>::new_from_quant(value)?,
                    ))
                }

                fn new_from_quant_clamped<FromQuant: $crate::values::quantizable::QuantizedSignedIntegerTrait>(
                    value: $crate::values::spatial::integer_signed::SignedIntegerSpatial<FromQuant, $num_dimensions>,
                ) -> Self {
                    <Self as $crate::values::spatial::integer_signed::SignedIntegerSpatialWrappedTrait<Q, $num_dimensions>>::wrap_unchecked(
                        $crate::values::spatial::integer_signed::SignedIntegerSpatial::<Q, $num_dimensions>::new_from_quant_clamped(value),
                    )
                }

                fn clamp_for_quantization<ClampFor: $crate::values::quantizable::QuantizedSignedIntegerTrait>(self) -> Self {
                    <Self as $crate::values::spatial::integer_signed::SignedIntegerSpatialWrappedTrait<Q, $num_dimensions>>::wrap_unchecked(
                        <Self as $crate::values::spatial::integer_signed::SignedIntegerSpatialWrappedTrait<Q, $num_dimensions>>::dewrap(self)
                            .clamp_for_quantization::<ClampFor>(),
                    )
                }

                fn clamp_for_quantization_level_runtime(
                    self,
                    level: $crate::values::quantizable::SignedIntegerQuantizationLevel,
                ) -> Self {
                    <Self as $crate::values::spatial::integer_signed::SignedIntegerSpatialWrappedTrait<Q, $num_dimensions>>::wrap_unchecked(
                        <Self as $crate::values::spatial::integer_signed::SignedIntegerSpatialWrappedTrait<Q, $num_dimensions>>::dewrap(self)
                            .clamp_for_quantization_level_runtime(level),
                    )
                }
            }

            impl<Q: $crate::values::quantizable::QuantizedSignedIntegerUnwrappedTrait>
                $crate::values::spatial::integer_signed::SignedIntegerSpatialWrappedTrait<Q, $num_dimensions> for $struct_name<Q>
            {
                type Spatial = $crate::values::spatial::integer_signed::SignedIntegerSpatial<Q, $num_dimensions>;

                const QUANT_ZEROS: Self = Self::const_new(
                    $crate::values::spatial::integer_signed::SignedIntegerSpatial::<Q, $num_dimensions>::QUANT_ZEROS,
                );

                fn wrap_unchecked(
                    value: $crate::values::spatial::integer_signed::SignedIntegerSpatial<Q, $num_dimensions>,
                ) -> Self {
                    Self(value)
                }

                fn dewrap(
                    self,
                ) -> $crate::values::spatial::integer_signed::SignedIntegerSpatial<Q, $num_dimensions> {
                    self.0
                }
            }

            impl<Q: $crate::values::quantizable::QuantizedSignedIntegerUnwrappedTrait>
                From<$crate::values::spatial::integer_signed::SignedIntegerSpatial<Q, $num_dimensions>>
                for $struct_name<Q>
            {
                fn from(value: $crate::values::spatial::integer_signed::SignedIntegerSpatial<Q, $num_dimensions>) -> Self {
                    Self(value)
                }
            }

            impl<Q: $crate::values::quantizable::QuantizedSignedIntegerUnwrappedTrait>
                AsRef<$crate::values::spatial::integer_signed::SignedIntegerSpatial<Q, $num_dimensions>>
                for $struct_name<Q>
            {
                fn as_ref(&self) -> &$crate::values::spatial::integer_signed::SignedIntegerSpatial<Q, $num_dimensions> {
                    &self.0
                }
            }

            impl<Q: $crate::values::quantizable::QuantizedSignedIntegerUnwrappedTrait>
                AsMut<$crate::values::spatial::integer_signed::SignedIntegerSpatial<Q, $num_dimensions>>
                for $struct_name<Q>
            {
                fn as_mut(&mut self) -> &mut $crate::values::spatial::integer_signed::SignedIntegerSpatial<Q, $num_dimensions> {
                    &mut self.0
                }
            }

            #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, ::serde::Serialize, ::serde::Deserialize)]
            $vis enum [<$struct_name Enum>] {
                I8($struct_name<i8>),
                I16($struct_name<i16>),
                I32($struct_name<i32>),
                I64($struct_name<i64>),
            }

            impl [<$struct_name Enum>] {
                pub fn new_from_quantized<FromQ: $crate::values::quantizable::QuantizedSignedIntegerUnwrappedTrait>(
                    value: $struct_name<FromQ>
                ) -> Self {
                    <Self as $crate::values::spatial::integer_signed::WrappedSignedIntegerSpatialEnum>::new_from_quantized(value)
                }

                pub fn into_quantization_unchecked<NewQ: $crate::values::quantizable::QuantizedSignedIntegerUnwrappedTrait>(
                    self
                ) -> $struct_name<NewQ> {
                    <Self as $crate::values::spatial::integer_signed::WrappedSignedIntegerSpatialEnum>::into_quantization_unchecked(self)
                }

                pub fn try_into_quantization<NewQ: $crate::values::quantizable::QuantizedSignedIntegerUnwrappedTrait>(
                    self
                ) -> Result<$struct_name<NewQ>, $crate::values::spatial::feagi_data_values_spatial_error::FeagiDataValuesSpatialError> {
                    <Self as $crate::values::spatial::integer_signed::WrappedSignedIntegerSpatialEnum>::try_into_quantization(self)
                }

                pub fn into_quantization_clamped<NewQ: $crate::values::quantizable::QuantizedSignedIntegerUnwrappedTrait>(
                    self
                ) -> $struct_name<NewQ> {
                    <Self as $crate::values::spatial::integer_signed::WrappedSignedIntegerSpatialEnum>::into_quantization_clamped(self)
                }
            }

            impl $crate::values::spatial::integer_signed::WrappedSignedIntegerSpatialEnum for [<$struct_name Enum>] {
                const NUM_DIMS: usize = $num_dimensions;
                type Shape<Q: $crate::values::quantizable::QuantizedSignedIntegerUnwrappedTrait> = $struct_name<Q>;

                fn get_level(&self) -> $crate::values::quantizable::SignedIntegerQuantizationLevel {
                    match self {
                        Self::I8(_) => $crate::values::quantizable::SignedIntegerQuantizationLevel::I8,
                        Self::I16(_) => $crate::values::quantizable::SignedIntegerQuantizationLevel::I16,
                        Self::I32(_) => $crate::values::quantizable::SignedIntegerQuantizationLevel::I32,
                        Self::I64(_) => $crate::values::quantizable::SignedIntegerQuantizationLevel::I64,
                    }
                }

                fn new_from_quantized<FromQ: $crate::values::quantizable::QuantizedSignedIntegerUnwrappedTrait>(
                    value: $struct_name<FromQ>
                ) -> Self {
                    match FromQ::LEVEL {
                        $crate::values::quantizable::SignedIntegerQuantizationLevel::I8 => {
                            Self::I8(
                                <$struct_name<i8> as $crate::values::spatial::integer_signed::SignedIntegerSpatialTrait<i8, $num_dimensions>>::new_from_quant_unchecked(
                                    value.dewrap(),
                                ),
                            )
                        }
                        $crate::values::quantizable::SignedIntegerQuantizationLevel::I16 => {
                            Self::I16(
                                <$struct_name<i16> as $crate::values::spatial::integer_signed::SignedIntegerSpatialTrait<i16, $num_dimensions>>::new_from_quant_unchecked(
                                    value.dewrap(),
                                ),
                            )
                        }
                        $crate::values::quantizable::SignedIntegerQuantizationLevel::I32 => {
                            Self::I32(
                                <$struct_name<i32> as $crate::values::spatial::integer_signed::SignedIntegerSpatialTrait<i32, $num_dimensions>>::new_from_quant_unchecked(
                                    value.dewrap(),
                                ),
                            )
                        }
                        $crate::values::quantizable::SignedIntegerQuantizationLevel::I64 => {
                            Self::I64(
                                <$struct_name<i64> as $crate::values::spatial::integer_signed::SignedIntegerSpatialTrait<i64, $num_dimensions>>::new_from_quant_unchecked(
                                    value.dewrap(),
                                ),
                            )
                        }
                    }
                }

                fn into_quantization_unchecked<NewQ: $crate::values::quantizable::QuantizedSignedIntegerUnwrappedTrait>(
                    self
                ) -> $struct_name<NewQ> {
                    match self {
                        Self::I8(value) => value.to_quantization_unchecked(),
                        Self::I16(value) => value.to_quantization_unchecked(),
                        Self::I32(value) => value.to_quantization_unchecked(),
                        Self::I64(value) => value.to_quantization_unchecked(),
                    }
                }

                fn try_into_quantization<NewQ: $crate::values::quantizable::QuantizedSignedIntegerUnwrappedTrait>(
                    self
                ) -> Result<$struct_name<NewQ>, $crate::values::spatial::feagi_data_values_spatial_error::FeagiDataValuesSpatialError> {
                    match self {
                        Self::I8(value) => value.try_to_quantization(),
                        Self::I16(value) => value.try_to_quantization(),
                        Self::I32(value) => value.try_to_quantization(),
                        Self::I64(value) => value.try_to_quantization(),
                    }
                }

                fn into_quantization_clamped<NewQ: $crate::values::quantizable::QuantizedSignedIntegerUnwrappedTrait>(
                    self
                ) -> $struct_name<NewQ> {
                    match self {
                        Self::I8(value) => value.to_quantization_clamped(),
                        Self::I16(value) => value.to_quantization_clamped(),
                        Self::I32(value) => value.to_quantization_clamped(),
                        Self::I64(value) => value.to_quantization_clamped(),
                    }
                }
            }
        }
    };
}
