[package]
name = "feagi-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "Systems for allowing a server to interact with FEAGI agents (clients)"

[dependencies]

[lints]
workspace = true
