//! `Scorecard` v1 — a portable, verifiable benchmark result bound to a connectome (ADR-012).
//!
//! A `Scorecard` is a separate, versioned record that *references* a genome/connectome
//! (never an in-place mutation), so one genome may carry many scorecards (one per
//! dataset/protocol) plus history. The pinned `connectome_hash` is the verification anchor:
//! any party can re-run the pinned connectome on the same dataset version + protocol and
//! confirm the metrics within tolerance (`status` becomes `verified` on an independent
//! match).
//!
//! Boundary (ADR-001/ADR-012): this crate only *generates* scorecards and supports local
//! self-verification. Publishing (user-triggered, public-genome prerequisite),
//! competitions, leaderboards, and hosted dataset assets are closed/desktop concerns; the
//! `visibility`/`status` fields exist so those flows can be driven without changing the
//! crate. Scorecards default to `visibility: local`.

use serde::{Deserialize, Serialize};

use super::common::{
    BackendKind, ConnectomeHash, ContentHash, DatasetAssetId, EvaluationProtocolVersion,
    GenomeVersionId, MetadataMap, PluginRef, ScorecardId, SplitId,
};

/// Wire/format version of the `Scorecard` contract.
pub const SCHEMA_VERSION: u32 = 1;

/// Verification status of a scorecard.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ScorecardStatus {
    /// Generated by the producer; not yet independently re-run.
    SelfReported,
    /// An independent re-run reproduced the metrics within tolerance.
    Verified,
}

/// Visibility/distribution state of a scorecard.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ScorecardVisibility {
    /// Stored locally for the user's own comparison (default).
    Local,
    /// Published (user-triggered; requires a public genome — enforced by the closed app).
    Published,
}

/// Records the execution environment a scorecard was produced on.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct BackendFingerprint {
    /// Execution backend (CPU baseline; GPU not verification-grade — ADR-003).
    pub backend: BackendKind,
    /// Free-form backend descriptor (e.g. driver/runtime details).
    pub descriptor: String,
    /// `feagi-trainer` crate version that produced the scorecard.
    pub trainer_version: String,
    /// feagi-core workspace version the run executed against.
    pub feagi_core_version: String,
}

/// A portable, verifiable benchmark result (design Section 6.1, ADR-012).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Scorecard {
    /// Wire/format version; must equal [`SCHEMA_VERSION`].
    pub schema_version: u32,
    /// Unique scorecard identifier.
    pub scorecard_id: ScorecardId,
    /// Pinned connectome under test — the verification anchor.
    pub connectome_hash: ConnectomeHash,
    /// Optional source-genome lineage reference.
    pub genome_version_id: Option<GenomeVersionId>,
    /// Dataset asset id (resolves locally now; hosted later — ADR-012).
    pub dataset_asset_id: DatasetAssetId,
    /// Human-facing dataset version string.
    pub dataset_version: String,
    /// Content hash binding the score to exact dataset bytes.
    pub dataset_content_hash: ContentHash,
    /// Versioned evaluation-protocol semantics.
    pub evaluation_protocol_version: EvaluationProtocolVersion,
    /// Metric pack that produced the metric values.
    pub metric_pack: PluginRef,
    /// Split the metrics were computed on.
    pub split_id: SplitId,
    /// Execution environment fingerprint.
    pub backend_fingerprint: BackendFingerprint,
    /// Metric name -> value (deterministically ordered).
    pub metrics: std::collections::BTreeMap<String, f64>,
    /// Verification status.
    pub status: ScorecardStatus,
    /// Visibility/distribution state.
    pub visibility: ScorecardVisibility,
    /// Free-form, deterministically ordered provenance metadata.
    pub metadata: MetadataMap,
}

#[cfg(test)]
mod tests {
    use super::super::common::PluginId;
    use super::*;
    use std::collections::BTreeMap;

    fn iris_scorecard() -> Scorecard {
        let mut metrics = BTreeMap::new();
        metrics.insert("accuracy".to_string(), 0.9667);
        metrics.insert("macro_f1".to_string(), 0.9655);
        Scorecard {
            schema_version: SCHEMA_VERSION,
            scorecard_id: ScorecardId("sc-0001".to_string()),
            connectome_hash: ConnectomeHash("sha256:connectome".to_string()),
            genome_version_id: None,
            dataset_asset_id: DatasetAssetId("local:iris".to_string()),
            dataset_version: "1.0.0".to_string(),
            dataset_content_hash: ContentHash("sha256:abc".to_string()),
            evaluation_protocol_version: EvaluationProtocolVersion("clf-v1".to_string()),
            metric_pack: PluginRef {
                id: PluginId("classification".to_string()),
                version: "1.0.0".to_string(),
            },
            split_id: SplitId("test".to_string()),
            backend_fingerprint: BackendFingerprint {
                backend: BackendKind::Cpu,
                descriptor: "x86_64-cpu".to_string(),
                trainer_version: "0.0.12".to_string(),
                feagi_core_version: "0.0.12".to_string(),
            },
            metrics,
            status: ScorecardStatus::SelfReported,
            visibility: ScorecardVisibility::Local,
            metadata: BTreeMap::new(),
        }
    }

    #[test]
    fn schema_version_is_pinned() {
        assert_eq!(iris_scorecard().schema_version, SCHEMA_VERSION);
    }

    #[test]
    fn defaults_are_local_and_self_reported() {
        let card = iris_scorecard();
        assert_eq!(card.visibility, ScorecardVisibility::Local);
        assert_eq!(card.status, ScorecardStatus::SelfReported);
    }

    #[test]
    fn json_round_trip_preserves_scorecard() {
        let card = iris_scorecard();
        let json = serde_json::to_string(&card).expect("serialize");
        let restored: Scorecard = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(card, restored);
    }
}
