[package]
name = "feagi-common-quantizable"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Defines core systems for Quantizable data types"


[features]

default = [
    "std",
    "support_64bit_indexing",
]

# ========================= Toggleable Features ========================= #
# Features that add certain libraries/crates that extend the functionality
# and performance of the FEAGI application
# In order of other features here, external crate features, feagi crate features

support_64bit_indexing = []
support_64bit_values = []

std = [
    "alloc",
]
alloc = [

]


[dependencies]
# DO NOT ADD ANY SIBLING FEAGI CEATES!
# Note: The official F8 crate is bad. Don't use it!
# DO NOT ADD ANY SIBLING FEAGI CEATES!
# DO NOT ADD ANY SIBLING FEAGI CEATES!
half = {workspace = true, default-features = false}
# DO NOT ADD ANY SIBLING FEAGI CEATES!
# DO NOT ADD ANY SIBLING FEAGI CEATES!
# DO NOT ADD ANY SIBLING FEAGI CEATES!
# DO NOT ADD ANY SIBLING FEAGI CEATES!
# DO NOT ADD ANY SIBLING FEAGI CEATES!
# DO NOT ADD ANY SIBLING FEAGI CEATES!
# DO NOT ADD ANY SIBLING FEAGI CEATES!
# DO NOT ADD ANY SIBLING FEAGI CEATES!
# DO NOT ADD ANY SIBLING FEAGI CEATES!
# DO NOT ADD ANY SIBLING FEAGI CEATES!
# DO NOT ADD ANY SIBLING FEAGI CEATES!
# DO NOT ADD ANY SIBLING FEAGI CEATES!
# DO NOT ADD ANY SIBLING FEAGI CEATES!
# DO NOT ADD ANY SIBLING FEAGI CEATES!