[package]
name = "feagi-genomic-context"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "IDs and Metadata used to identify and describe structures within FEAGI Genomes"

[features]

default = [
    "std",
]

# ========================= Toggleable Features ========================= #
# Features that add certain libraries/crates that extend the functionality
# and performance of the FEAGI application
# In order of Directly activated crates, other features here, external crate features, feagi crate features

std = [
    "alloc",
    "feagi-basis/std",
    "serde/std", "serde_json/std", "ahash/std"
]

alloc = [
    "serde_json",
    "feagi-basis/alloc",
    "serde/alloc", "serde/derive", "serde_json/alloc", "ahash/serde",
]

[dependencies]
feagi-basis = {path = "../feagi-basis" }

# External crates
paste = { workspace = true }
ahash = { workspace = true}
serde = { workspace = true}
serde_json = { workspace = true, optional = true}
uuid = { version = "1.24.0", features = ["v4", "v7"] }


[lints]
workspace = true
