/// Helper structs to make dealing with multiple quantizations / models less annoying
use feagi_data::quantization_levels::feagi_index_quantization::FeagiIndexQuantization;
use crate::standard::npu::burst_engine::sync_implementations::rayon::data::neuron::model_quantized_data::feagi_advanced_model::ModelFeagiAdvanced;

macro_rules! quant_default_with_neurons {
    ($struct_name:ident) => {
        impl<FIQ: FeagiIndexQuantization> Default for $struct_name<FIQ> {
            fn default() -> Self {
                Self {
                    cortical_data: CorticalModelIndexedVector::new_empty(),
                    psp_uniformity: NeuronModelIndexedVector::new_empty(),
                    neuron_data: NeuronModelIndexedVector::new_empty(),
                }
            }
        }
    };
}

// TODO this should be generated by macro
// TODO coincidentally, this can also be used as connectome file storage...

/// Vectors of neuron model data by quantization and model
pub struct NeuronModelData<FIQ: FeagiIndexQuantization> {
    pub feagi_advanced: ModelFeagiAdvanced<FIQ>, // TODO this should be macroized and expanded!
}

impl<FIQ: FeagiIndexQuantization> NeuronModelData<FIQ> {}

impl<FIQ: FeagiIndexQuantization> Default for NeuronModelData<FIQ> {
    fn default() -> Self {
        Self {
            feagi_advanced: ModelFeagiAdvanced::default(),
        }
    }
}

#[doc(hidden)]
mod feagi_advanced_model {
    use feagi_data::quantization_levels::feagi_index_quantization::FeagiIndexQuantization;
    use feagi_models::cortical_area::neuron_model_implementations::feagi_advanced::data::{
        FeagiAdvancedModelCorticalData, FeagiAdvancedModelNeuronData,
    };
    use feagi_models::cortical_area::neuron_model_implementations::feagi_advanced::quantization::FeagiAdvancedModelStandardQuant;
    use feagi_models::wrapped_index_collections::{CorticalModelIndexedVector, NeuronModelIndexedVector};

    #[doc(hidden)]
    pub struct ModelFeagiAdvanced<FIQ: FeagiIndexQuantization> {
        pub quantization_standard: QuantizationStandard<FIQ>,
    }

    impl<FIQ: FeagiIndexQuantization> Default for ModelFeagiAdvanced<FIQ> {
        fn default() -> Self {
            Self {
                quantization_standard: Default::default(),
            }
        }
    }

    #[doc(hidden)]
    pub struct QuantizationStandard<FIQ: FeagiIndexQuantization> {
        pub cortical_data:
            CorticalModelIndexedVector<FIQ::CorticalAreaIndexCountQuant, FeagiAdvancedModelCorticalData<FeagiAdvancedModelStandardQuant>>,
        pub psp_uniformity: NeuronModelIndexedVector<FIQ::NeuronIndexQuant, FeagiAdvancedModelNeuronData<FeagiAdvancedModelStandardQuant>>,
        pub neuron_data: NeuronModelIndexedVector<FIQ::NeuronIndexQuant, FeagiAdvancedModelNeuronData<FeagiAdvancedModelStandardQuant>>,
    }

    quant_default_with_neurons!(QuantizationStandard);
}
