[package]
name = "cortical-unit-definitions"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Holds sole macro definitions for sensor and motor cortical units for compile time definitions"

[dependencies]
# No dependencies or anything, this crate literally just exports macros