[package]
name = "feagi-data"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

####################################################################################
################################ IMPORTANT WARNING! ################################
####################################################################################
# Since sibling crates depend on this crate (which is a rust antipattern but makes
# sense given the current context), this crate must NOT depend on any other
# sibling / parent FEAGI crates, as it risks causing recursive compilation issues!


[features]
std = [  # do we support the standard library?
    "alloc",
    "half/std",
    #"dep:ahash"
]
alloc = [ # Do we support dynamic allocating memory?
    "half/alloc"
]
support_64bit_indexing = [] # Allow 64 bit indexing. This is pretty rare. Not compatible with some targets
support_64bit_values = [] # Allow 64 bit values (IE: Membrane potentials). Extremely rare! Not compatible with some targets
support_wgpu = []
defmt = []

[dependencies]
# DO NOT ADD ANY SIBLING FEAGI CEATES!
# These are child subcrates
feagi-logging-and-errors = {path = "../../feagi-logging-and-errors" }
feagi-bitpacking = {path = "../feagi-bitpacking" }
# Note: The official F8 crate is bad. Don't use it!
# DO NOT ADD ANY SIBLING FEAGI CEATES!
# DO NOT ADD ANY SIBLING FEAGI CEATES!
paste = {workspace = true}
half = {workspace = true, default-features = false}
ahash = {workspace = true} # TODO this probably shouldnt be entirely toggled by std?
# DO NOT ADD ANY SIBLING FEAGI CEATES!
# DO NOT ADD ANY SIBLING FEAGI CEATES!
# DO NOT ADD ANY SIBLING FEAGI CEATES!
# DO NOT ADD ANY SIBLING FEAGI CEATES!
# DO NOT ADD ANY SIBLING FEAGI CEATES!
# DO NOT ADD ANY SIBLING FEAGI CEATES!
# DO NOT ADD ANY SIBLING FEAGI CEATES!

