use crate::values::quantizable::QuantizedIndexCountTrait;
use core::ops::Range;

/// Contains a vector of incrementing (by start / end index) ranges that are not overlapping, as well as indexes to those
/// ranges in order of decrementing lengths of each range. Inserting a range will attempt to insert
/// a range maintaining order, but if the range touches any neighbors, those neighbors are merged
/// to produce a contiguous range instead
pub struct CombiningRangeVector<Q: QuantizedIndexCountTrait> {
    ranges: Vec<Range<Q>>,
    indexes_sorted_by_length: Vec<Q>,
    total_value: Q,
}

impl<Q: QuantizedIndexCountTrait> CombiningRangeVector<Q> {
    pub fn new() -> Self {
        Self {
            ranges: vec![],
            indexes_sorted_by_length: vec![],
            total_value: Q::QUANT_ZERO,
        }
    }

    /// Returns the number of contained ranges
    pub fn get_number_ranges(&self) -> Q {
        Q::from_usize(self.ranges.len())
    }

    /// Returns the total value of all lengths of all ranges summed together
    pub fn get_all_ranges_sum(&self) -> Q {
        self.total_value
    }

    /// Does a reverse search through the internal ranges to find the smallest range that can
    /// contain the given length. If one is found, a new range of length starting at the found
    /// range is returned after that given range had the part being removed cut out, with
    /// reordering of internal index sorting updated as well. If no suitable range is found,
    /// returns None.
    pub fn try_pop_range_containing_length(&mut self, length: Q) -> Option<Range<Q>> {
        // NOTE: Since we are looking through a list of ranges in decrementing order, use the
        // internal sorted length vector to quickly jump to the index of each range!
        todo!()
    }

    /// Undoes the effects of `try_pop_range_containing_length` by returning the Range it produced,
    /// and restoring the inner state of this struct at that point. Note that this must be called
    /// immediately after `try_pop_range_containing_length` with the range it returned, otherwise
    /// this struct will be left in an invalid state.
    pub fn undo_pop_range_containing_length(&mut self, undoing_range: Range<Q>) {
        todo!()
    }

    /// Attempts to insert a range maintaining the order to the ranges internal vector. If
    /// the range shares a side with a neighbor, they are merged. The ordered indexes will also be
    /// updated as a result.
    ///  NOTE: It is assumed that any inserting range may not overlap into existing ranges!
    pub fn insert_range_merge(&mut self, range: Range<Q>) -> Result<(), ()> {
        todo!()
    }

    /// Undoes the effects of `insert_range_merge` by removing the range generated by that function,
    /// recutting any existing ranges that may have been previously merged as well.
    /// Note this must be called immediately after `try_pop_range_containing_length` otherwise
    /// this struct may be left in an invalid state
    pub fn undo_insert_range_merge(&mut self, undoing_range: Range<Q>) {
        todo!()
    }

    /// Clears all values in the internal vectors without deallocating memory
    pub fn clear(&mut self) {
        self.ranges.clear();
        self.indexes_sorted_by_length.clear();
        self.total_value = Q::QUANT_ZERO;
    }

    /// Deallocates any unused memory at the end of the vectors
    pub fn shrink_to_fit(&mut self) {
        self.ranges.shrink_to_fit();
        self.indexes_sorted_by_length.shrink_to_fit();
    }
}
