[package]
name = "feagi-npu-structures"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Abstractions for neural structures used by the FEAGI Burst Engine"

[features]

default = ["default-linux-x86"]

default-win-x86 = [
    "std",
    "rayon"
]
default-win-arm = [
    "std",
    "rayon"
]
default-mac-x86 = [
    "std",
    "rayon"
]
default-mac-arm = [
    "std",
    "rayon"
]
default-linux-x86 = [
    "std",
    "rayon"
]
default-linux-arm = [
    "std",
    "rayon"
]

default-wasm = []
default-embedded-generic = [] # break this into more types later

std = [ # allows use of the std library
    "alloc",
    "dep:ahash",
    "feagi-structures/std"
]
alloc = [ # allows use of alloc (through core, not strictly std)
    "serde/alloc",
    "feagi-structures/alloc"
]
rayon = [
    "dep:rayon",
    "std",
    "feagi-structures/rayon"
]
support_64bit_indexing = [ # Allow 64 bit indexing. This is pretty rare. Not compatible with WASM or Embedded
    "feagi-structures/support_64bit_indexing"
]
support_64bit_values = [ # Allow 64 bit values (IE: Membrane potentials). Extremely rare! Not compatible with WASM or Embedded
    "feagi-structures/support_64bit_values"
]

[dependencies]
feagi-structures = {path = "../../feagi-structures"}
feagi-npu-neuron-models = {path = "feagi-npu-neuron-models"}
serde = { workspace = true, default-features = false, features = [] }
ahash = { workspace = true, default-features = false, optional = true}
rayon = { workspace = true, optional = true}
half = { workspace = true, default-features = false, features = [] } # STD enables autoarch detection, which we may not want
paste = { workspace = true }
