[package]
name = "feagi-rest-basis"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "Shared logic and config structs for REST servers and clients"

# TODO logic for generating OpenAPI and swagger docs

[features]

std = [
    "alloc",
    "feagi-basis/std", "feagi-io-basis/std",
    "thingbuf/std", "serde/std", "serde_json/std"
]

alloc = [
    "feagi-basis/alloc", "feagi-io-basis/alloc",
    "thingbuf/alloc", "serde/alloc", "serde_json/alloc"
]

open_api_and_swagger = [] # TODO

[dependencies]

# Sibling Crates
feagi-io-basis = {path = "../../feagi-io-basis"}

# Root Crates
feagi-basis = {path = "../../../../feagi-basis"}

# External Crates
paste = {workspace = true}
serde = {workspace = true}
serde_json = {workspace = true}
thingbuf = {workspace = true, features = ["static"]}
