[package]
name = "feagi-transport"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "Root library extending Zenoh for use in FEAGI as a transport medium"

[features]

std = [
    "alloc",
    "serde/std", "serde_json/std"
]

alloc = [
    "serde/alloc", "serde_json/alloc"
]

transport_rest = []

transport_rest_swagger = [
    "transport_rest"
]

transport_ws = []

# TODO other transports, compression, auth?

[dependencies]


# External Crates
paste = {workspace = true}
serde = { workspace = true, features = ["derive"] }
serde_json = {workspace = true, features = []}
zenoh = {workspace = true, features = ["default", "unstable", "internal", "plugins", "runtime_plugins"]}
tokio = {version = "1.53.2", features = ["full"]}


[lints]
workspace = true
