[package]
name = "feagi-npu-common"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "Contains common structs used between FEAGI NPU subcrates"

[features]

default = [
    "std",
    "use-rayon"
]

# ========================= Toggleable Features ========================= #
# Features that add certain libraries/crates that extend the functionality
# and performance of the FEAGI application
# In order of Directly activated crates, other features here, external crate features, feagi crate features

# Allows use of mutlithreading to accomplish large parallel tasks faster. Requires std.
use-rayon = [
    "rayon",
    "std",
]


std = [
    "alloc",
]

alloc = [
    "serde", "serde_json",
]


[dependencies]

# External crates
# DO NOT HAVE ANY DEPENDENCIES ON ANYTHING FROM FEAGI NPU!
paste = { workspace = true}
ahash = { workspace = true}
serde = { workspace = true, optional = true}
serde_json = { workspace = true, optional = true}
rayon = { workspace = true, optional = true}

feagi-data = {path = "../../feagi-data"}



[lints]
workspace = true
