[package]
name = "feagi-npu-burst-rayon"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "Rayon burst engine logic for multithread / core CPU neuron processing"


[dependencies]
feagi-data = {path = "../../../feagi-data" }
feagi-models = {path = "../../../feagi-models" }
feagi-logging-and-errors = {path = "../../../feagi-logging-and-errors" }
feagi-genomic-context = {path = "../../../feagi-genomic-context" }

# External crates
paste = { workspace = true}
half = {workspace = true}
ahash = { workspace = true}
rayon = { workspace = true, optional = true}