[package]
name = "feagi-npu"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "Contains the logic for the neural processing unit and their interfacing"


[features]

default = [
    "std", # "engine-composable-rayon"
]

# ========================= Standard Toggleable Features ========================= #

std = [
    "alloc",
    "feagi-npu-burst-engines/std",
    "futures/std", "futures/executor",
    "ahash/std", "ahash/runtime-rng",
    "serde/std",
    "serde_json/std",

]

alloc = [
    "serde_json",
    'feagi-npu-burst-engines/alloc',
    'futures/alloc',
    "serde/alloc",
]

# ========================= Crate Level Features ========================= #

# CPU burst engine that uses multiple cpu threads to process neurons (includes variants that are optimized for different uses, cpus)
engines-rayon = [
    "std",
    "feagi-npu-burst-engines/engines-rayon"
]


# Family of engines for the ESP32 family of chips and boards
engines-esp32 = [
    "feagi-npu-burst-engines/engines-esp32"
]

# ========================= Platform Specific Dependencies ========================= #

# NOTE: Right now none of these are being used, but that may change later

# For MicroSlop operating systems
#[target.'cfg(windows)'.dependencies]

# For Pingu and Tim Apple operating systems
#[target.'cfg(unix)'.dependencies]

# For Internet Explorer 6
#[target.'cfg(target_arch = "wasm32")'.dependencies]

# For ESP32 Xtensa boards (not all ESP32 devices are Xtensa! Some are Risc-V!)
#[target.'cfg(target_arch = "xtensa")'.dependencies]




[dependencies]
feagi-npu-burst-engines = {path = "feagi-npu-burst-engines"}
feagi-data = {path = "../feagi-data"}
feagi-models = {path = "../feagi-models" }
feagi-logging-and-errors = {path = "../feagi-logging-and-errors"}
feagi-genomic-context = {path = "../feagi-genomic-context"}


# External crates
paste = { workspace = true}
futures = {workspace = true, default-features = false}
ahash = { workspace = true, default-features = false}
serde = { workspace = true, default-features = false}
# Toggled external crates
serde_json = { workspace = true, optional = true}

# TODO we should tie these to workspace


[lints]
workspace = true
