[package]
name = "feagi-npu"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "Contains the logic for the neural processing unit and their interfacing"


[features]

default = [
    "std", "composable", "engine-composable-rayon"
]

# ========================= Standard Toggleable Features ========================= #

std = [
    "alloc",
    "feagi-npu-burst-engines/std",
    "futures/std", "futures/executor",
    "ahash/std", "ahash/runtime-rng",
    "serde/std",
    "serde_json/std",

]

alloc = [
    "serde_json",
    'feagi-npu-burst-engines/alloc',
    'futures/alloc',
    "serde/alloc",
]

# ========================= Crate Level Features ========================= #

# Enables interfaces for editing connectomes, such as adding / removing cortical areas and mappings
composable = [
    "std",
    "feagi-npu-burst-engines/composable"
]

# CPU burst composable engine that uses multiple cpu threads to process neurons
engine-composable-rayon = [
    "std",
    "composable",
    "feagi-npu-burst-engines/engine-composable-rayon"
]

# A non-composable engine for the ESP32 family of microcontrollers
engine-noncomposable-esp32 = [
    "feagi-npu-burst-engines/engine-noncomposable-esp32"
]

[dependencies]
feagi-data = {path = "../feagi-data"}
feagi-models = {path = "../feagi-models" }
feagi-logging-and-errors = {path = "../feagi-logging-and-errors"}
feagi-genomic-context = {path = "../feagi-genomic-context"}
feagi-npu-burst-engines = {path = "feagi-npu-burst-engines"}

# External crates
paste = { workspace = true}
futures = {workspace = true, default-features = false}
ahash = { workspace = true, default-features = false}
serde = { workspace = true, default-features = false}
# Toggled external crates
serde_json = { workspace = true, optional = true}

# TODO we should tie these to workspace


[lints]
workspace = true
