[package]
name = "feagi-basis"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "Base data structures and methods used throughout FEAGI"

[features]

default = [
    "std",
    "serde_json",
]

std = [
    "alloc",
    "thiserror/std", "serde/std", "serde_json/std", "ahash/std", "thingbuf/std",
    "feagi-basis-quantization/std", "feagi-basis-collections/std",
]

alloc = [
    "serde/alloc", "serde_json/alloc", "thingbuf/alloc",
    "feagi-basis-quantization/alloc", "feagi-basis-collections/alloc"
]

# Allows use of mutlithreading to accomplish large parallel tasks faster. Requires std.
rayon = [
    "dep:rayon",
    "feagi-basis-collections/rayon",
    "std",
]

# Support for serializing and deserializng JSON via serde
serde_json = [
    "dep:serde_json",
    "feagi-basis-collections/serde_json",
    "ahash/serde"
]



[dependencies]
# Sub Crates
feagi-basis-quantization = {path = "feagi-basis-quantization" }
feagi-basis-collections = {path = "feagi-basis-collections"}

# Root Crates
# NONE! THIS CRATE MUST NOT DEPEND ON OTHER FEAGI ROOT CRATES

# External crates
thiserror = {workspace = true}
paste = { workspace = true }
ahash = { workspace = true}
serde = { workspace = true, features = ["derive"]}
heapless = {workspace = true}
thingbuf = {workspace = true, features = ["static"]} # TODO review features
serde_json = { workspace = true, optional = true}
rayon = { workspace = true, optional = true}



[lints]
workspace = true
