[package]
name = "feagi-basis"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "Base data structures and methods used throughout FEAGI"

[features]

default = [
    "std",
    "serde_json", "rayon"
]

std = [
    "alloc",
    "thiserror/std", "serde/std", "serde_json/std", "ahash/std", "thingbuf/std", "half/std",
]

alloc = [
    "serde/alloc", "serde_json/alloc", "serde_arrays/alloc", "thingbuf/alloc", "half/alloc", "heapless/alloc",
]

# Allows use of mutlithreading to accomplish large parallel tasks faster. Requires std.
rayon = [
    "dep:rayon",
    "std",
]


[dependencies]
feagi-basis-proc-common = {path = "feagi-basis-proc-common"}

# Root Crates
# NONE! THIS CRATE MUST NOT DEPEND ON OTHER FEAGI ROOT CRATES

# External crates
thiserror = {workspace = true}
paste = { workspace = true }
ahash = { workspace = true, features = ["serde"]}
serde = { workspace = true, features = ["derive"]}
serde_arrays = { workspace = true }
heapless = {workspace = true}
thingbuf = {workspace = true, features = ["static"]} # TODO review features
serde_json = { workspace = true, optional = true}
rayon = { workspace = true, optional = true}
half = { workspace = true, default-features = false, features = ["serde"] }




[lints]
workspace = true
