mod feagi_byte_structure_compatible;
mod feagi_byte_structure;
mod feagi_byte_structure_type;

pub use feagi_byte_structure::FeagiByteStructure as FeagiByteStructure;
pub use feagi_byte_structure_type::FeagiByteStructureType;
pub use feagi_byte_structure_compatible::FeagiByteStructureCompatible;