[package]
name = "feagi-common-collections"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Common Collections based on quantizable data types"

[features]

default = [
    "std",
    "support_64bit_indexing",
]

# ========================= Toggleable Features ========================= #
# Features that add certain libraries/crates that extend the functionality
# and performance of the FEAGI application
# In order of other features here, external crate features, feagi crate features

support_64bit_indexing = []
support_64bit_values = []

std = [
    "alloc",
]
alloc = [

]

[dependencies]
feagi-common-quantizable = {path = "../feagi-common-quantizable"}
feagi-common-spatial = {path = "../feagi-common-spatial"}
feagi-common-logging-and-errors = {path = "../feagi-common-logging-and-errors"}
