[package]
name = "feagi-npu-burst-rayon"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "Rayon burst engine logic for multithread / core CPU neuron processing"

[features]

# Note: nested sub crates should not have default features in order to prevent confusion upstream

# ========================= Standard Toggleable Features ========================= #

std = [
    "alloc",
]

alloc = [

]

[dependencies]
# Sub Crates

# Sibling Crates
feagi-npu-burst-core = {path = "../feagi-npu-burst-core"}

# Parent Crates
feagi-brain-models = {path = "../../../feagi-brain-models"}

# Root Crates
feagi-data = {path = "../../../../feagi-data" }
feagi-logging-and-errors = {path = "../../../../feagi-logging-and-errors" }

# External Crates
paste = { workspace = true}
serde = {workspace = true} # Required by FeagiError
heapless = {workspace = true, default-features = false}
half = {workspace = true}
ahash = { workspace = true}
rayon = { workspace = true}