[package]
name = "feagi-basis-error-logging"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Contains FEAGI error macro generator and logger facade to swap between `log` and `defmt` (or neither)"

[features]

enable_log_facade = [
    "log"
]

enable_defmt = [
    "defmt"
]

[dependencies]

# Sub Crates
feagi-basis-error-logging-proc = { path = "feagi-basis-error-logging-proc" }

# Sibling Crates
# NONE! ALL OTHER SIBLING CRATES DEPEND ON THIS!

# Root Crates
# NONE! NOTHING WITHIN BASIS CAN USE OTHER ROOT CRATES!

# External Crates
log = {workspace = true, optional = true}
defmt = {workspace = true, optional = true}
