[package]
name = "feagi-cns-structures"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "Various structures used to describe the structure and state of the FEAGI Brain"

[features]

std = [
    "alloc",
    "serde/std", "base64/std"
]

alloc = [
    "serde/alloc", "base64/alloc"
]



[dependencies]
# Workspace Crates
feagi-basis = {path = "../feagi-basis"}

# External Crates
serde = {workspace = true, features = ["derive"]}
base64 = {workspace = true, features = []}

[lints]
workspace = true
