[package]
name = "feagi-io-rest"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "Allows Request / Response communication over HTTP Rest for servers and clients."


[features]

# NOTE: The Implementation of the routing is arguably cursed. All implementations are enabled here. However, this crate
# in its lib.rs file uses the combination of features to extern the correct crate only

std = [
    "alloc",
    "dep:feagi-rest-server-std"
]

alloc = []

############ Endpoint Types ############



# Enables a webserver
feagi-rest-server = [
    "dep:feagi-rest-server-std",
    #"dep:feagi-rest-server-no-std"
]

# Enables generation of OpenAPI Docs and the swagger page on the server
open_api_and_swagger = [
    "feagi-rest-server",
    "feagi-rest-basis/open_api_and_swagger"
]

feagi-rest-client = [] # TODO add clients

############ Async Runtimes ############

smol = [
    "std",
    "feagi-rest-server-std/smol"
]

# TODO more asyncs

[dependencies]

# Child Crates
feagi-rest-basis = {path = "feagi-rest-basis"} # TODO move OpenAPI / Swag generation here?
feagi-rest-server-std = {path = "feagi-rest-server-std", optional = true}
#feagi-rest-server-no-std = {path = "feagi-rest-server-no-std", optional = true} TODO

# NOTE: This crate does very little itself, hence its sparse requirements