[package]
name = "feagi-basis-macros"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Holds common Macros and dependent structs / traits, incluing FEAGI error macro generator and logger facade to swap between `log` and `defmt`"

[features]

std = []

enable_log_facade = [
    "log"
]

enable_defmt = [
    "defmt"
]

[dependencies]

# Sub Crates
feagi-macros-proc = { path = "feagi-macros-proc" }

# Sibling Crates
# NONE! ALL OTHER SIBLING CRATES DEPEND ON THIS!

# Root Crates
# NONE! NOTHING WITHIN BASIS CAN USE OTHER ROOT CRATES!

# External Crates
log = {workspace = true, optional = true}
defmt = {workspace = true, optional = true}
