[package]
name = "feagi-correspondence-io"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "Defines the interfaces to exchange data by FEAGI agents and servers"

[features]
# subcrates should not have default in order to avoid confusion

std = [
    "alloc",
    "feagi-io-basis/std", "feagi-io-rest/std",
    "feagi-basis/std",
    "serde/std", "serde_json/std",
]

alloc = [
    "serde_json",
    "feagi-io-basis/alloc", "feagi-io-rest/alloc",
    "feagi-basis/alloc",
    "serde/alloc", "serde_json/alloc",
]

############ Endpoint Types ############

# HTTP Server Support
rest-server = [
    "dep:feagi-io-rest"
]

# Adds the swagger page to the HTTP Server
rest-server-swagger = [ # TODO does nothing right now
    "rest-server"
]

############ Async Runtimes ############

# Allow the use of the smol runtime
smol = [
    "feagi-io-rest/smol"
]

[dependencies]
# Sub Crates
feagi-io-basis = {path = "feagi-io-basis"}
feagi-io-rest = {path = "feagi-io-rest", optional = true}

# Sibling Crates

# Root Crates
feagi-basis = {path = "../../feagi-basis"}

# External crates
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, optional = true, features = [] }