[package]
name = "feagi-data-neuron"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "Structures related to Neuron Data used in FEAGI"

[features]

# subcrates should not have default in order to avoid confusion

std = [
    "alloc",
    "feagi-basis/std",
    "half/std", "serde/std", "serde_json/std"
]

alloc = [
    "feagi-basis/alloc",
    "half/alloc", "serde/alloc", "serde_json/alloc"
]

rayon = [
    "std"
]

[dependencies]
# Root Crates
feagi-basis = {path = "../../feagi-basis"}

# External Crates
paste = { workspace = true }
half = {workspace = true}
serde = { workspace = true}
serde_json = { workspace = true, optional = true}