[package]
name = "feagi-brain"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true

[features]

default = [
    "std", # "engine-composable-rayon"
]

# ========================= Standard Toggleable Features ========================= #

std = [
    "alloc",
    "ahash/std",
    "serde/std",
    "serde_json/std",
    "uuid/std"

]

alloc = [
    "serde_json",
    "serde/alloc",
]

[dependencies]
# Sub Crates
feagi-brain-models = {path = "feagi-brain-models"}
feagi-brain-npu = {path = "feagi-brain-npu"}

# Root Crates
feagi-basis = {path = "../feagi-basis" }

# External crates
paste = { workspace = true}
ahash = { workspace = true, default-features = false}
serde = { workspace = true, default-features = false}
serde_json = { workspace = true, optional = true}
uuid = { workspace = true, default-features = false, features = ["v7", "serde"] }

[lints]
workspace = true
