[package]
name = "feagi-npu-burst-engines"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "Contains the Burst Engines for various hardwares, which handle the processing of the connectome"

# TODO features to control what burst engines are accessible

[features]

# Note: nested sub crates should not have default features in order to prevent confusion upstream

# ========================= Standard Toggleable Features ========================= #

std = [
    "alloc",
]

alloc = [

]

# ========================= Standard Toggleable Features ========================= #

# Enables interfaces for editing connectomes, such as adding / removing cortical areas and mappings
composable = [
    "std"
]

# CPU burst composable engine that uses multiple cpu threads to process neurons
engine-composable-rayon = [
    "std",
    "composable",
    "feagi-npu-burst-rayon"
]

# A non composable engine for the ESP32 family of microcontrollers
engine-noncomposable-esp32 = [

]

[dependencies]
feagi-npu-burst-core = {path = "feagi-npu-burst-core"}
feagi-npu-burst-rayon = {path = "feagi-npu-burst-rayon", optional = true}

feagi-data = {path = "../../feagi-data" }
feagi-models = {path = "../../feagi-models" }
feagi-logging-and-errors = {path = "../../feagi-logging-and-errors" }

paste = {workspace = true}