use feagi_structures::feagi_data::create_quantized_index_count_wrapper;
use feagi_structures::feagi_data::feagi_ecs::collection::FeagiECSCollection;
use feagi_structures::feagi_data::feagi_ecs::element::FeagiECSElement;
use feagi_structures::feagi_data::feagi_ecs::element_set::FeagiECSElementSet;
use feagi_structures::feagi_data::shared_quantization_sets::FeagiGlobalQuantization;

create_quantized_index_count_wrapper!(SynapseIndex);
create_quantized_index_count_wrapper!(AxonBundleIndex);




/// Root Synapse Data Trait. Denotes any data / context per synapse, including occasionally
/// tertiary cortical area information
pub trait SynapseDataCommon<FGIQ>:
FeagiECSElement
where
    FGIQ: FeagiGlobalQuantization,
{
    // Cant store data for unknown device

    // Extend this with per synapse data such as weights
}



/// Root Axon Bundle Header Data Trait. Denotes any data / context for an entire axon bundle
/// outside the actual synapses and their mappings.
pub trait AxonBundleHeaderDataCommon<FGIQ>:
FeagiECSElement
where
    FGIQ: FeagiGlobalQuantization,
{
    // Cant store data for unknown device

    // Extend this with per axon bundle header data, such as shared parameters across all synapses
    // This struct is generated by the mapping-generators, so do not include things like
    // cortical indexes, but rather only properties that the user can somehow set through bv
}


/// Structure that handles redirectomgf
pub trait SynapseIndexRedirectCommon<FGIQ, SynapseData, AxonHeaderData>:
FeagiECSElementSet<SynapseData> // Technically we store AxonHeaderData too, but lets just define one to make the trait happy
where
    FGIQ: FeagiGlobalQuantization,
    SynapseData: SynapseDataCommon<FGIQ>,
    AxonHeaderData: AxonBundleHeaderDataCommon<FGIQ>
{
    
}



/// Responsible for storing the synapse datas for a single mapping (axon bundle), and the
/// axon header itself
pub trait AxonBundleCommon<FGIQ, SynapseData, AxonHeaderData>:
FeagiECSElementSet<SynapseData>
where
    FGIQ: FeagiGlobalQuantization,
    SynapseData: SynapseDataCommon<FGIQ>,
    AxonHeaderData: AxonBundleHeaderDataCommon<FGIQ>
{
    // Cant store data for unknown device

    // Responsible for storing the synapse datas for a single mapping (axon bundle), and the
    // axon header itself. The only information this should store is things like
    // cortical indexes and FCL read/write offsets

}
