[package]
name = "feagi-structures"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "The most core library, defines the basic data types used by FEAGI, as well as some processors to modify them"

[features]
default = ["default-linux-x86"]

default-win-x86 = [
    "std", 
    "ndarray", 
    "rayon"
]
default-win-arm = [
    "std", 
    "ndarray", 
    "rayon"
]
default-mac-x86 = [
    "std", 
    "ndarray", 
    "rayon"
]
default-mac-arm = [
    "std", 
    "ndarray", 
    "rayon"
]
default-linux-x86 = [
    "std", 
    "ndarray", 
    "rayon"
]
default-linux-arm = [
    "std", 
    "ndarray", 
    "rayon"
]
default-wasm = []
default-embedded-generic = ["defmt"] # break this into more types later

# TODO It is possible to have serde functionality without std / alloc, but for now we will feature gate it
# TODO think of a better way to toggle tracing off in embedded / wasm envs

std = [
    "feagi-data/std",
    "feagi-genome-definitions/std",
    "feagi-potential-voxels/std",
    "alloc",
    "ahash/std",
    "dep:tracing"]
alloc = [
    "feagi-data/alloc",
    "feagi-genome-definitions/alloc",
    "feagi-potential-voxels/alloc",
    "dep:serde",
    "dep:serde_json",
    "half/serde",
    "ahash/serde",
]
support_64bit_indexing = [ # Allow 64 bit indexing. This is pretty rare. Not compatible with WASM, Embedded
    "feagi-data/support_64bit_indexing",
    "feagi-potential-voxels/support_64bit_indexing",
]
support_64bit_values = [ # Allow 64 bit values (IE: Membrane potentials). Extremely rare! Not compatible with WASM, Embedded
    "feagi-data/support_64bit_values",
    "feagi-potential-voxels/support_64bit_values",
]
support_wgpu = [
    "feagi-data/support_wgpu",
    "feagi-potential-voxels/support_wgpu",
]


defmt = ["dep:defmt"]
ndarray = ["dep:ndarray"]
rayon = ["dep:rayon", "std"]

[dependencies]
# Subcrates
feagi-data = {path = "feagi-data"} # This crate has sibling crates dependent on it. Be Cautious!
feagi-genome-definitions = {path = "feagi-genome-definitions"}
feagi-potential-voxels = {path = "feagi-potential-voxels"}


# External crates
serde = { workspace = true, optional = true, default-features = false, features = ["alloc", "derive"] }
serde_json = { workspace = true, optional = true}
half = { workspace = true, default-features = false, features = [] } # STD enables autoarch detection, which we may not want
ahash = { workspace = true, default-features = true} # TODO we need default features to compile, see what required feature is missing from features above!
uuid = { workspace = true, features = ["v7"] } # TODO Special notes for embedded and WASM support, discuss later!
ndarray = { workspace = true, optional = true}
rayon = { workspace = true, optional = true}
defmt = {workspace = true, optional = true}
tracing = {workspace = true, optional = true}
paste = { workspace = true } # Despite only using the paste macro, it seems that the crate cannot be in dev dependencies
base64 = { version = "0.22.1" } # TODO special notes about alloc, discuss later!
