[package]
name = "feagi-structures"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "The most core library, defines the basic data types used by FEAGI, as well as some processors to modify them"

# TODO investigate possible split between neuron structures and certain genomic identifiers

[features]
default = ["std", "ndarray", "rayon", "support_64bit_indexing_quantization"]

std = ["alloc", "dep:ahash"] # allows use of the std library
alloc = [] # allows use of alloc (through core, not strictly std)
defmt = ["dep:defmt"]
ndarray = ["dep:ndarray"]
rayon = ["dep:rayon", "std"]
support_64bit_indexing_quantization = []

[dependencies]
defmt = {workspace = true, optional = true}
ahash = { workspace = true, optional = true}
serde = { workspace = true }
serde_json = { workspace = true}
ndarray = { workspace = true, optional = true}
rayon = { workspace = true, optional = true}
uuid = { workspace = true } # TODO check STD compabtility
half = {workspace = true, default-features = false, features = []} # STD enables autoarch detection, which we may not want
tracing = "0.1.44" # TODO we may need to move this with wherever we move the ulog


base64 = "0.22.1" # TODO move to workspace

[dev-dependencies]
paste = "1.0.15"