/// Helper structs to make dealing with multiple quantizations / models less annoying
use feagi_data::quantization_levels::feagi_index_quantization::FeagiIndexQuantization;
use feagi_models::neuron::model_generated::model_type_and_quantization::{NeuronModelType, NeuronModelTypeAndQuantizationNested};
use feagi_models::neuron::models::feagi_advanced::FeagiAdvancedModelQuantizationLevel;
use feagi_models::neuron::neuron_model::NeuronModel;
use feagi_models::neuron::neuron_model_quantization::NeuronModelQuantization;
use feagi_models::wrapped_index_collections::{CorticalModelIndex, NeuronModelIndex};
use crate::engines::rayon::data::neuron::model_quantized_data::feagi_advanced_model::ModelFeagiAdvanced;

macro_rules! quant_default_with_neurons {
    ($struct_name:ident) => {
    impl<FIQ: FeagiIndexQuantization> Default for $struct_name<FIQ> {
        fn default() -> Self {
            Self {
                cortical_data: CorticalModelIndexedVector::new_empty(),
                psp_uniformity: NeuronModelIndexedVector::new_empty(),
                neuron_data: NeuronModelIndexedVector::new_empty(),
            }
        }
    }
    };
}

// TODO this should be generated by macro
// TODO coincidentally, this can also be used as connectome file storage...


/// Vectors of neuron model data by quantization and model
pub struct NeuronModelData<FIQ: FeagiIndexQuantization> {
    pub feagi_advanced: ModelFeagiAdvanced<FIQ>
    // TODO this should be macroized and expanded!
}

impl<FIQ: FeagiIndexQuantization> NeuronModelData<FIQ> {

    pub fn allocate_for_new_area<NMQ: NeuronModelQuantization, NM: NeuronModel<FIQ, NMQ>>(&mut self, number_neurons: FIQ::NeuronIndexQuant) -> (&mut NM::CorticalData, &mut NM::NeuronData){
        match NM::NEURON_MODEL_AND_QUANTIZATION {
            NeuronModelTypeAndQuantizationNested::FeagiAdvanced(quant) => {
                match quant {
                    FeagiAdvancedModelQuantizationLevel::Standard => {
                        // some functions may need to be added
                        // append to end of vector, return mut reference to it
                        let cortical_ref: &mut NM::CorticalData  = self.feagi_advanced.quantization_standard.cortical_data.append_single_mut(NM::CorticalData::default());
                        //self.feagi_advanced.quantization_standard.psp_uniformity.extend(CorticalModelIndex::QUANT_ONE, 0.0);
                        // TODO PSP uniformity
                        // append to end of vector, return mut slice to it
                        let neuron_slice: &mut [NM::NeuronData] = self.feagi_advanced.quantization_standard.neuron_data.extend_mut(NeuronModelIndex::from(number_neurons), NM::NeuronData::default());
                        (cortical_ref, neuron_slice)
                    }
                }
            }
        }
    }

}

impl<FIQ: FeagiIndexQuantization> Default for NeuronModelData<FIQ> {
    fn default() -> Self {
        Self {
            feagi_advanced: ModelFeagiAdvanced::default()
        }
    }
}




#[doc(hidden)]
mod feagi_advanced_model {
    use feagi_data::quantization_levels::feagi_index_quantization::FeagiIndexQuantization;
    use feagi_models::neuron::models::feagi_advanced::{FeagiAdvancedModelCorticalData, FeagiAdvancedModelNeuronData, FeagiAdvancedModelStandardQuant};
    use feagi_models::wrapped_index_collections::{CorticalModelIndexedVector, NeuronModelIndexedVector};

    #[doc(hidden)]
    pub struct ModelFeagiAdvanced<FIQ: FeagiIndexQuantization> {
        pub quantization_standard: QuantizationStandard<FIQ>
    }

    impl<FIQ: FeagiIndexQuantization> Default for ModelFeagiAdvanced<FIQ> {
        fn default() -> Self {
            Self {
                quantization_standard: Default::default()
            }
        }
    }


    #[doc(hidden)]
    pub struct QuantizationStandard<FIQ: FeagiIndexQuantization> {
        pub cortical_data: CorticalModelIndexedVector
        <
            FIQ::CorticalAreaIndexCountQuant,
            FeagiAdvancedModelCorticalData<FeagiAdvancedModelStandardQuant>
        >,
        pub psp_uniformity: NeuronModelIndexedVector
        <
            FIQ::NeuronIndexQuant,
            FeagiAdvancedModelNeuronData<FeagiAdvancedModelStandardQuant>,
        >,
        pub neuron_data: NeuronModelIndexedVector
        <
            FIQ::NeuronIndexQuant,
            FeagiAdvancedModelNeuronData<FeagiAdvancedModelStandardQuant>,
        >,
    }

    quant_default_with_neurons!(QuantizationStandard);



}

