use feagi_data::quantization_levels::feagi_index_quantization::FeagiIndexQuantization;
use feagi_npu_common::wrapped_indexes::{CorticalModelIndexedVector, NeuronModelIndexedVector};
use feagi_npu_models::neuron_models::feagi_standard::data::{
    FeagiStandardModelCorticalData, FeagiStandardModelNeuronData,
};
use feagi_npu_models::neuron_models::feagi_standard::quantization::FeagiStandardModelStandard32BitQuant;

// TODO these should be generated by macro

//region Neuron
/// Stores all neuron model categories (which are further divided by their quantization)
pub struct NeuronModelDataVecs<FIQ: FeagiIndexQuantization> {
    pub feagi_standard_data: FeagiStandardModelNeuronVecs<FIQ>,
}

pub struct FeagiStandardModelNeuronVecs<FIQ: FeagiIndexQuantization> {
    pub standard_32_bit: NeuronModelIndexedVector<
        FIQ::NeuronIndexCountQuant,
        FeagiStandardModelNeuronData<FeagiStandardModelStandard32BitQuant>,
    >,
}

//endregion

//region Cortical

/// Stores all cortical model categories (which are further divided by their quantization)
pub struct CorticalModelDataVecs<FIQ: FeagiIndexQuantization> {
    pub feagi_standard_data: FeagiStandardModelCorticalVecs<FIQ>,
}

pub struct FeagiStandardModelCorticalVecs<FIQ: FeagiIndexQuantization> {
    pub standard_32_bit: CorticalModelIndexedVector<
        FIQ::NeuronIndexCountQuant,
        FeagiStandardModelCorticalData<FeagiStandardModelStandard32BitQuant>,
    >,
}

//endregion
