[package]
name = "feagi-common"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Shared code used by all other FEAGI Crates"

[features]

default = [
    "std",
    "use-rayon"
]

# ========================= Toggleable Features ========================= #
# Features that add certain libraries/crates that extend the functionality
# and performance of the FEAGI application
# In order of Directly activated crates, other features here, external crate features, feagi crate features

# Allows use of mutlithreading to accomplish large parallel tasks faster. Requires std.
use-rayon = [
    "rayon",
    "std",
]


std = [
    "alloc",
    "serde/std", "serde_json/std", "ahash/std"
]

alloc = [
    "serde", "serde_json",
    "serde/alloc", "serde/derive", "serde_json/alloc", "ahash/serde",
]



[dependencies]
# Subcrates
feagi-common-quantizable = {path = "feagi-common-quantizable"} # This crate has sibling crates dependent on it. Be Cautious!
feagi-common-spatial = {path = "feagi-common-spatial"}

# External crates
paste = { workspace = true }
ahash = { workspace = true}
serde = { workspace = true, optional = true}
serde_json = { workspace = true, optional = true}
rayon = { workspace = true, optional = true}



uuid = { workspace = true, features = ["v7"] } # TODO Special notes for embedded and WASM support, discuss later!
base64 = { version = "0.22.1" } # TODO special notes about alloc, discuss later!
