pub mod dimensional_storage_traits;
pub mod shared_structs;
pub mod sensory_neurons;
pub mod core_neurons;
pub mod inter_neurons;
pub mod motor_neurons;
mod shared_funcs_ram;
mod dimensional_cortical_neurons_collection;
mod neuron_models;
mod neuron_collection;
