[package]
name = "feagi-io-basis"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "Shared Structs and Traits between feagi-correspondence-io subcrates"

[dependencies]
