[package]
name = "feagi-brain-templates"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
build = "build.rs"

[lib]
path = "src/lib.rs"

[dependencies]
