//! Macros that generate strongly-typed *wrappers* around the contiguous
//! quantized collections defined in [`crate::collections::linear::contiguous_data`].
//!
//! Just like [`crate::create_wrapped_quantized_index`] produces a distinct
//! newtype around a single quantized index value, these macros produce distinct
//! newtypes around whole collections. The generated types re-expose the usual
//! interface (length, element access, sub-slicing, iteration, unsafe parallel
//! access), but the *index* type in every signature is a caller-supplied wrapped
//! index (as generated by [`crate::create_wrapped_quantized_index`]) rather than
//! the raw [`QuantizedIndexCountTrait`](crate::values::quantizable::QuantizedIndexCountTrait)
//! value. This makes it impossible to accidentally mix indices/collections of
//! different logical kinds, with zero runtime cost (`#[repr(transparent)]`).
//!
//! Because the sub-slicing methods return the *wrapped* slice types, generate
//! the slice wrappers first, then pass their names into the vector / array /
//! mutable-slice macros:
//!
//! ```ignore
//! create_wrapped_quantized_index!(pub NeuronIndex);
//! create_wrapped_contiguous_slice!(pub NeuronSlice, NeuronIndex);
//! create_wrapped_contiguous_slice_mut!(pub NeuronSliceMut, NeuronIndex, NeuronSlice);
//! create_wrapped_contiguous_vector!(pub NeuronVector, NeuronIndex, NeuronSlice, NeuronSliceMut);
//! create_wrapped_contiguous_array!(pub NeuronArray, NeuronIndex, NeuronSlice, NeuronSliceMut);
//! ```

/// Generates a strongly-typed wrapper around
/// [`QuantizedContiguousSlice`](crate::collections::linear::contiguous_data::QuantizedContiguousSlice).
///
/// Parameters: `$(#[meta])* $vis $StructName, $WrappedIndex`.
#[macro_export]
macro_rules! create_wrapped_contiguous_slice {
    (
        $(#[$meta:meta])*
        $vis:vis $struct_name:ident,
        $index:ident
    ) => {
        $(#[$meta])*
        #[repr(transparent)]
        $vis struct $struct_name<'a, Q: $crate::values::quantizable::QuantizedIndexCountTrait, V: Clone + Copy>(
            $crate::collections::linear::contiguous_data::QuantizedContiguousSlice<'a, Q, V>
        );

        impl<'a, Q: $crate::values::quantizable::QuantizedIndexCountTrait, V: Clone + Copy> Clone
            for $struct_name<'a, Q, V>
        {
            fn clone(&self) -> Self {
                *self
            }
        }

        impl<'a, Q: $crate::values::quantizable::QuantizedIndexCountTrait, V: Clone + Copy> Copy
            for $struct_name<'a, Q, V>
        {}

        impl<'a, Q: $crate::values::quantizable::QuantizedIndexCountTrait, V: Clone + Copy>
            $struct_name<'a, Q, V>
        {
            /// Wraps a raw shared slice.
            pub fn new(data: &'a [V]) -> Self {
                Self($crate::collections::linear::contiguous_data::QuantizedContiguousSlice::new(data))
            }

            /// Wraps the underlying (unwrapped) collection type.
            pub fn from_inner(
                inner: $crate::collections::linear::contiguous_data::QuantizedContiguousSlice<'a, Q, V>,
            ) -> Self {
                Self(inner)
            }

            /// Unwraps into the underlying collection type.
            pub fn into_inner(
                self,
            ) -> $crate::collections::linear::contiguous_data::QuantizedContiguousSlice<'a, Q, V> {
                self.0
            }

            /// Borrows the backing storage as a regular shared slice.
            pub fn as_slice(&self) -> &[V] {
                use $crate::collections::linear::contiguous_data::QuantizedContiguousTrait;
                self.0.as_slice()
            }

            /// Number of elements, expressed in the wrapped index type.
            pub fn len(&self) -> $index<Q> {
                use $crate::collections::linear::contiguous_data::QuantizedContiguousTrait;
                <$index<Q>>::from(self.0.len())
            }

            /// Returns `true` if there are no elements.
            pub fn is_empty(&self) -> bool {
                use $crate::collections::linear::contiguous_data::QuantizedContiguousTrait;
                self.0.is_empty()
            }

            /// Copies out the element at `index`, or `None` if out of bounds.
            pub fn get(&self, index: $index<Q>) -> Option<V> {
                use $crate::collections::linear::contiguous_data::QuantizedContiguousTrait;
                self.0.get(index.const_deref())
            }

            /// Borrows a half-open sub-range as another wrapped slice.
            pub fn subslice(
                &self,
                range: core::ops::Range<$index<Q>>,
            ) -> Result<$struct_name<'_, Q, V>, $crate::collections::feagi_data_collections_error::FeagiDataCollectionError> {
                use $crate::collections::linear::contiguous_data::QuantizedContiguousTrait;
                let inner = self.0.subslice(range.start.const_deref()..range.end.const_deref())?;
                Ok($struct_name(inner))
            }

            /// Iterates over shared references to the elements.
            pub fn iter(&self) -> core::slice::Iter<'_, V> {
                use $crate::collections::linear::contiguous_data::QuantizedContiguousTrait;
                self.0.iter()
            }

            /// Returns a shared reference to the element at `index`, without
            /// bounds checking.
            ///
            /// # Safety
            /// - `index` must be in bounds.
            pub unsafe fn get_par(&self, index: $index<Q>) -> &V {
                use $crate::collections::linear::contiguous_data::QuantizedContiguousParTrait;
                unsafe { self.0.get_par(index.const_deref()) }
            }
        }

        impl<'a, Q: $crate::values::quantizable::QuantizedIndexCountTrait, V: Clone + Copy>
            core::ops::Index<$index<Q>> for $struct_name<'a, Q, V>
        {
            type Output = V;
            fn index(&self, index: $index<Q>) -> &V {
                &self.0[index.const_deref()]
            }
        }

        impl<'a, Q: $crate::values::quantizable::QuantizedIndexCountTrait, V: Clone + Copy>
            From<&'a [V]> for $struct_name<'a, Q, V>
        {
            fn from(value: &'a [V]) -> Self {
                Self::new(value)
            }
        }
    };
}

/// Generates a strongly-typed wrapper around
/// [`QuantizedContiguousSliceMut`](crate::collections::linear::contiguous_data::QuantizedContiguousSliceMut).
///
/// Parameters: `$(#[meta])* $vis $StructName, $WrappedIndex, $WrappedSlice`.
/// `$WrappedSlice` is the read-only wrapped slice type returned by the immutable
/// [`subslice`](Self::subslice) method (generate it first).
#[macro_export]
macro_rules! create_wrapped_contiguous_slice_mut {
    (
        $(#[$meta:meta])*
        $vis:vis $struct_name:ident,
        $index:ident,
        $slice:ident
    ) => {
        $(#[$meta])*
        #[repr(transparent)]
        $vis struct $struct_name<'a, Q: $crate::values::quantizable::QuantizedIndexCountTrait, V: Clone + Copy>(
            $crate::collections::linear::contiguous_data::QuantizedContiguousSliceMut<'a, Q, V>
        );

        impl<'a, Q: $crate::values::quantizable::QuantizedIndexCountTrait, V: Clone + Copy>
            $struct_name<'a, Q, V>
        {
            /// Wraps a raw mutable slice.
            pub fn new(data: &'a mut [V]) -> Self {
                Self($crate::collections::linear::contiguous_data::QuantizedContiguousSliceMut::new(data))
            }

            /// Wraps the underlying (unwrapped) collection type.
            pub fn from_inner(
                inner: $crate::collections::linear::contiguous_data::QuantizedContiguousSliceMut<'a, Q, V>,
            ) -> Self {
                Self(inner)
            }

            /// Unwraps into the underlying collection type.
            pub fn into_inner(
                self,
            ) -> $crate::collections::linear::contiguous_data::QuantizedContiguousSliceMut<'a, Q, V> {
                self.0
            }

            /// Returns the underlying mutable slice, keeping the original lifetime.
            pub fn into_slice_mut(self) -> &'a mut [V] {
                self.0.into_slice_mut()
            }

            /// Creates a shorter-lived, exclusive re-borrow of this view.
            pub fn reborrow(&mut self) -> $struct_name<'_, Q, V> {
                $struct_name(self.0.reborrow())
            }

            /// Borrows the backing storage as a regular shared slice.
            pub fn as_slice(&self) -> &[V] {
                use $crate::collections::linear::contiguous_data::QuantizedContiguousTrait;
                self.0.as_slice()
            }

            /// Mutably borrows the backing storage as a regular slice.
            pub fn as_mut_slice(&mut self) -> &mut [V] {
                use $crate::collections::linear::contiguous_data::QuantizedContiguousMutTrait;
                self.0.as_mut_slice()
            }

            /// Number of elements, expressed in the wrapped index type.
            pub fn len(&self) -> $index<Q> {
                use $crate::collections::linear::contiguous_data::QuantizedContiguousTrait;
                <$index<Q>>::from(self.0.len())
            }

            /// Returns `true` if there are no elements.
            pub fn is_empty(&self) -> bool {
                use $crate::collections::linear::contiguous_data::QuantizedContiguousTrait;
                self.0.is_empty()
            }

            /// Copies out the element at `index`, or `None` if out of bounds.
            pub fn get(&self, index: $index<Q>) -> Option<V> {
                use $crate::collections::linear::contiguous_data::QuantizedContiguousTrait;
                self.0.get(index.const_deref())
            }

            /// Mutably borrows the element at `index`, or `None` if out of bounds.
            pub fn get_mut(&mut self, index: $index<Q>) -> Option<&mut V> {
                use $crate::collections::linear::contiguous_data::QuantizedContiguousMutTrait;
                self.0.get_mut(index.const_deref())
            }

            /// Overwrites the element at `index`, returning the previous value if
            /// the index was in bounds.
            pub fn set(&mut self, index: $index<Q>, value: V) -> Option<V> {
                use $crate::collections::linear::contiguous_data::QuantizedContiguousMutTrait;
                self.0.set(index.const_deref(), value)
            }

            /// Borrows a half-open sub-range as a read-only wrapped slice.
            pub fn subslice(
                &self,
                range: core::ops::Range<$index<Q>>,
            ) -> Result<$slice<'_, Q, V>, $crate::collections::feagi_data_collections_error::FeagiDataCollectionError> {
                use $crate::collections::linear::contiguous_data::QuantizedContiguousTrait;
                let inner = self.0.subslice(range.start.const_deref()..range.end.const_deref())?;
                Ok($slice::from_inner(inner))
            }

            /// Mutably borrows a half-open sub-range as another wrapped mutable slice.
            pub fn subslice_mut(
                &mut self,
                range: core::ops::Range<$index<Q>>,
            ) -> Result<$struct_name<'_, Q, V>, $crate::collections::feagi_data_collections_error::FeagiDataCollectionError> {
                use $crate::collections::linear::contiguous_data::QuantizedContiguousMutTrait;
                let inner = self.0.subslice_mut(range.start.const_deref()..range.end.const_deref())?;
                Ok($struct_name(inner))
            }

            /// Iterates over shared references to the elements.
            pub fn iter(&self) -> core::slice::Iter<'_, V> {
                use $crate::collections::linear::contiguous_data::QuantizedContiguousTrait;
                self.0.iter()
            }

            /// Iterates over mutable references to the elements.
            pub fn iter_mut(&mut self) -> core::slice::IterMut<'_, V> {
                use $crate::collections::linear::contiguous_data::QuantizedContiguousMutTrait;
                self.0.iter_mut()
            }

            /// Returns a shared reference to the element at `index`, without
            /// bounds checking.
            ///
            /// # Safety
            /// - `index` must be in bounds.
            pub unsafe fn get_par(&self, index: $index<Q>) -> &V {
                use $crate::collections::linear::contiguous_data::QuantizedContiguousParTrait;
                unsafe { self.0.get_par(index.const_deref()) }
            }

            /// Returns a mutable reference to the element at `index` through a
            /// shared `&self`, enabling parallel mutation of disjoint indices.
            ///
            /// # Safety
            /// - `index` must be in bounds.
            /// - Concurrent callers must only ever target disjoint indices.
            pub unsafe fn get_mut_par(&self, index: $index<Q>) -> &mut V {
                use $crate::collections::linear::contiguous_data::QuantizedContiguousParMutTrait;
                unsafe { self.0.get_mut_par(index.const_deref()) }
            }
        }

        impl<'a, Q: $crate::values::quantizable::QuantizedIndexCountTrait, V: Clone + Copy>
            core::ops::Index<$index<Q>> for $struct_name<'a, Q, V>
        {
            type Output = V;
            fn index(&self, index: $index<Q>) -> &V {
                &self.0[index.const_deref()]
            }
        }

        impl<'a, Q: $crate::values::quantizable::QuantizedIndexCountTrait, V: Clone + Copy>
            core::ops::IndexMut<$index<Q>> for $struct_name<'a, Q, V>
        {
            fn index_mut(&mut self, index: $index<Q>) -> &mut V {
                &mut self.0[index.const_deref()]
            }
        }

        impl<'a, Q: $crate::values::quantizable::QuantizedIndexCountTrait, V: Clone + Copy>
            From<&'a mut [V]> for $struct_name<'a, Q, V>
        {
            fn from(value: &'a mut [V]) -> Self {
                Self::new(value)
            }
        }
    };
}

/// Generates a strongly-typed wrapper around
/// [`QuantizedContiguousVector`](crate::collections::linear::contiguous_data::QuantizedContiguousVector).
///
/// Parameters:
/// `$(#[meta])* $vis $StructName, $WrappedIndex, $WrappedSlice, $WrappedSliceMut`.
#[macro_export]
macro_rules! create_wrapped_contiguous_vector {
    (
        $(#[$meta:meta])*
        $vis:vis $struct_name:ident,
        $index:ident,
        $slice:ident,
        $slice_mut:ident
    ) => {
        $(#[$meta])*
        #[repr(transparent)]
        $vis struct $struct_name<Q: $crate::values::quantizable::QuantizedIndexCountTrait, V: Clone + Copy>(
            $crate::collections::linear::contiguous_data::QuantizedContiguousVector<Q, V>
        );

        impl<Q: $crate::values::quantizable::QuantizedIndexCountTrait, V: Clone + Copy> Clone
            for $struct_name<Q, V>
        {
            fn clone(&self) -> Self {
                Self(self.0.clone())
            }
        }

        impl<Q: $crate::values::quantizable::QuantizedIndexCountTrait, V: Clone + Copy>
            $struct_name<Q, V>
        {
            /// Builds a vector of `number_values` elements, each set to `filling_value`.
            pub fn new_uniform(number_values: $index<Q>, filling_value: V) -> Self {
                Self($crate::collections::linear::contiguous_data::QuantizedContiguousVector::new_uniform(
                    number_values.const_deref(),
                    filling_value,
                ))
            }

            /// Wraps an existing `Vec` without copying.
            pub fn from_vec(data: Vec<V>) -> Self {
                Self($crate::collections::linear::contiguous_data::QuantizedContiguousVector::from_vec(data))
            }

            /// Consumes the wrapper, returning the backing `Vec`.
            pub fn into_vec(self) -> Vec<V> {
                self.0.into_vec()
            }

            /// Wraps the underlying (unwrapped) collection type.
            pub fn from_inner(
                inner: $crate::collections::linear::contiguous_data::QuantizedContiguousVector<Q, V>,
            ) -> Self {
                Self(inner)
            }

            /// Unwraps into the underlying collection type.
            pub fn into_inner(
                self,
            ) -> $crate::collections::linear::contiguous_data::QuantizedContiguousVector<Q, V> {
                self.0
            }

            /// Borrows the backing storage as a regular shared slice.
            pub fn as_slice(&self) -> &[V] {
                use $crate::collections::linear::contiguous_data::QuantizedContiguousTrait;
                self.0.as_slice()
            }

            /// Mutably borrows the backing storage as a regular slice.
            pub fn as_mut_slice(&mut self) -> &mut [V] {
                use $crate::collections::linear::contiguous_data::QuantizedContiguousMutTrait;
                self.0.as_mut_slice()
            }

            /// Number of elements, expressed in the wrapped index type.
            pub fn len(&self) -> $index<Q> {
                use $crate::collections::linear::contiguous_data::QuantizedContiguousTrait;
                <$index<Q>>::from(self.0.len())
            }

            /// Returns `true` if there are no elements.
            pub fn is_empty(&self) -> bool {
                use $crate::collections::linear::contiguous_data::QuantizedContiguousTrait;
                self.0.is_empty()
            }

            /// Copies out the element at `index`, or `None` if out of bounds.
            pub fn get(&self, index: $index<Q>) -> Option<V> {
                use $crate::collections::linear::contiguous_data::QuantizedContiguousTrait;
                self.0.get(index.const_deref())
            }

            /// Mutably borrows the element at `index`, or `None` if out of bounds.
            pub fn get_mut(&mut self, index: $index<Q>) -> Option<&mut V> {
                use $crate::collections::linear::contiguous_data::QuantizedContiguousMutTrait;
                self.0.get_mut(index.const_deref())
            }

            /// Overwrites the element at `index`, returning the previous value if
            /// the index was in bounds.
            pub fn set(&mut self, index: $index<Q>, value: V) -> Option<V> {
                use $crate::collections::linear::contiguous_data::QuantizedContiguousMutTrait;
                self.0.set(index.const_deref(), value)
            }

            /// Borrows the whole vector as a read-only wrapped slice.
            pub fn as_quantized_slice(&self) -> $slice<'_, Q, V> {
                use $crate::collections::linear::contiguous_data::QuantizedContiguousTrait;
                $slice::from_inner(self.0.as_quantized_slice())
            }

            /// Mutably borrows the whole vector as a wrapped mutable slice.
            pub fn as_quantized_slice_mut(&mut self) -> $slice_mut<'_, Q, V> {
                use $crate::collections::linear::contiguous_data::QuantizedContiguousMutTrait;
                $slice_mut::new(self.0.as_mut_slice())
            }

            /// Borrows a half-open sub-range as a read-only wrapped slice.
            pub fn subslice(
                &self,
                range: core::ops::Range<$index<Q>>,
            ) -> Result<$slice<'_, Q, V>, $crate::collections::feagi_data_collections_error::FeagiDataCollectionError> {
                use $crate::collections::linear::contiguous_data::QuantizedContiguousTrait;
                let inner = self.0.subslice(range.start.const_deref()..range.end.const_deref())?;
                Ok($slice::from_inner(inner))
            }

            /// Mutably borrows a half-open sub-range as a wrapped mutable slice.
            pub fn subslice_mut(
                &mut self,
                range: core::ops::Range<$index<Q>>,
            ) -> Result<$slice_mut<'_, Q, V>, $crate::collections::feagi_data_collections_error::FeagiDataCollectionError> {
                use $crate::collections::linear::contiguous_data::QuantizedContiguousMutTrait;
                let inner = self.0.subslice_mut(range.start.const_deref()..range.end.const_deref())?;
                Ok($slice_mut::from_inner(inner))
            }

            /// Iterates over shared references to the elements.
            pub fn iter(&self) -> core::slice::Iter<'_, V> {
                use $crate::collections::linear::contiguous_data::QuantizedContiguousTrait;
                self.0.iter()
            }

            /// Iterates over mutable references to the elements.
            pub fn iter_mut(&mut self) -> core::slice::IterMut<'_, V> {
                use $crate::collections::linear::contiguous_data::QuantizedContiguousMutTrait;
                self.0.iter_mut()
            }

            /// Returns a shared reference to the element at `index`, without
            /// bounds checking.
            ///
            /// # Safety
            /// - `index` must be in bounds.
            pub unsafe fn get_par(&self, index: $index<Q>) -> &V {
                use $crate::collections::linear::contiguous_data::QuantizedContiguousParTrait;
                unsafe { self.0.get_par(index.const_deref()) }
            }

            /// Returns a mutable reference to the element at `index` through a
            /// shared `&self`, enabling parallel mutation of disjoint indices.
            ///
            /// # Safety
            /// - `index` must be in bounds.
            /// - Concurrent callers must only ever target disjoint indices.
            pub unsafe fn get_mut_par(&self, index: $index<Q>) -> &mut V {
                use $crate::collections::linear::contiguous_data::QuantizedContiguousParMutTrait;
                unsafe { self.0.get_mut_par(index.const_deref()) }
            }
        }

        impl<Q: $crate::values::quantizable::QuantizedIndexCountTrait, V: Clone + Copy>
            core::ops::Index<$index<Q>> for $struct_name<Q, V>
        {
            type Output = V;
            fn index(&self, index: $index<Q>) -> &V {
                &self.0[index.const_deref()]
            }
        }

        impl<Q: $crate::values::quantizable::QuantizedIndexCountTrait, V: Clone + Copy>
            core::ops::IndexMut<$index<Q>> for $struct_name<Q, V>
        {
            fn index_mut(&mut self, index: $index<Q>) -> &mut V {
                &mut self.0[index.const_deref()]
            }
        }

        impl<Q: $crate::values::quantizable::QuantizedIndexCountTrait, V: Clone + Copy>
            From<Vec<V>> for $struct_name<Q, V>
        {
            fn from(value: Vec<V>) -> Self {
                Self::from_vec(value)
            }
        }
    };
}

/// Generates a strongly-typed wrapper around
/// [`QuantizedContiguousArray`](crate::collections::linear::contiguous_data::QuantizedContiguousArray).
///
/// Parameters:
/// `$(#[meta])* $vis $StructName, $WrappedIndex, $WrappedSlice, $WrappedSliceMut`.
#[macro_export]
macro_rules! create_wrapped_contiguous_array {
    (
        $(#[$meta:meta])*
        $vis:vis $struct_name:ident,
        $index:ident,
        $slice:ident,
        $slice_mut:ident
    ) => {
        $(#[$meta])*
        #[repr(transparent)]
        $vis struct $struct_name<Q: $crate::values::quantizable::QuantizedIndexCountTrait, V: Clone + Copy, const N: usize>(
            $crate::collections::linear::contiguous_data::QuantizedContiguousArray<Q, V, N>
        );

        impl<Q: $crate::values::quantizable::QuantizedIndexCountTrait, V: Clone + Copy, const N: usize> Clone
            for $struct_name<Q, V, N>
        {
            fn clone(&self) -> Self {
                *self
            }
        }

        impl<Q: $crate::values::quantizable::QuantizedIndexCountTrait, V: Clone + Copy, const N: usize> Copy
            for $struct_name<Q, V, N>
        {}

        impl<Q: $crate::values::quantizable::QuantizedIndexCountTrait, V: Clone + Copy, const N: usize>
            $struct_name<Q, V, N>
        {
            /// Builds an array with every element set to `filling_value`.
            pub fn new_uniform(filling_value: V) -> Self {
                Self($crate::collections::linear::contiguous_data::QuantizedContiguousArray::new_uniform(filling_value))
            }

            /// Wraps an existing array.
            pub fn from_array(data: [V; N]) -> Self {
                Self($crate::collections::linear::contiguous_data::QuantizedContiguousArray::from_array(data))
            }

            /// Consumes the wrapper, returning the backing array.
            pub fn into_array(self) -> [V; N] {
                self.0.into_array()
            }

            /// Wraps the underlying (unwrapped) collection type.
            pub fn from_inner(
                inner: $crate::collections::linear::contiguous_data::QuantizedContiguousArray<Q, V, N>,
            ) -> Self {
                Self(inner)
            }

            /// Unwraps into the underlying collection type.
            pub fn into_inner(
                self,
            ) -> $crate::collections::linear::contiguous_data::QuantizedContiguousArray<Q, V, N> {
                self.0
            }

            /// Borrows the backing storage as a regular shared slice.
            pub fn as_slice(&self) -> &[V] {
                use $crate::collections::linear::contiguous_data::QuantizedContiguousTrait;
                self.0.as_slice()
            }

            /// Mutably borrows the backing storage as a regular slice.
            pub fn as_mut_slice(&mut self) -> &mut [V] {
                use $crate::collections::linear::contiguous_data::QuantizedContiguousMutTrait;
                self.0.as_mut_slice()
            }

            /// Number of elements, expressed in the wrapped index type.
            pub fn len(&self) -> $index<Q> {
                use $crate::collections::linear::contiguous_data::QuantizedContiguousTrait;
                <$index<Q>>::from(self.0.len())
            }

            /// Returns `true` if there are no elements.
            pub fn is_empty(&self) -> bool {
                use $crate::collections::linear::contiguous_data::QuantizedContiguousTrait;
                self.0.is_empty()
            }

            /// Copies out the element at `index`, or `None` if out of bounds.
            pub fn get(&self, index: $index<Q>) -> Option<V> {
                use $crate::collections::linear::contiguous_data::QuantizedContiguousTrait;
                self.0.get(index.const_deref())
            }

            /// Mutably borrows the element at `index`, or `None` if out of bounds.
            pub fn get_mut(&mut self, index: $index<Q>) -> Option<&mut V> {
                use $crate::collections::linear::contiguous_data::QuantizedContiguousMutTrait;
                self.0.get_mut(index.const_deref())
            }

            /// Overwrites the element at `index`, returning the previous value if
            /// the index was in bounds.
            pub fn set(&mut self, index: $index<Q>, value: V) -> Option<V> {
                use $crate::collections::linear::contiguous_data::QuantizedContiguousMutTrait;
                self.0.set(index.const_deref(), value)
            }

            /// Borrows the whole array as a read-only wrapped slice.
            pub fn as_quantized_slice(&self) -> $slice<'_, Q, V> {
                use $crate::collections::linear::contiguous_data::QuantizedContiguousTrait;
                $slice::from_inner(self.0.as_quantized_slice())
            }

            /// Mutably borrows the whole array as a wrapped mutable slice.
            pub fn as_quantized_slice_mut(&mut self) -> $slice_mut<'_, Q, V> {
                use $crate::collections::linear::contiguous_data::QuantizedContiguousMutTrait;
                $slice_mut::new(self.0.as_mut_slice())
            }

            /// Borrows a half-open sub-range as a read-only wrapped slice.
            pub fn subslice(
                &self,
                range: core::ops::Range<$index<Q>>,
            ) -> Result<$slice<'_, Q, V>, $crate::collections::feagi_data_collections_error::FeagiDataCollectionError> {
                use $crate::collections::linear::contiguous_data::QuantizedContiguousTrait;
                let inner = self.0.subslice(range.start.const_deref()..range.end.const_deref())?;
                Ok($slice::from_inner(inner))
            }

            /// Mutably borrows a half-open sub-range as a wrapped mutable slice.
            pub fn subslice_mut(
                &mut self,
                range: core::ops::Range<$index<Q>>,
            ) -> Result<$slice_mut<'_, Q, V>, $crate::collections::feagi_data_collections_error::FeagiDataCollectionError> {
                use $crate::collections::linear::contiguous_data::QuantizedContiguousMutTrait;
                let inner = self.0.subslice_mut(range.start.const_deref()..range.end.const_deref())?;
                Ok($slice_mut::from_inner(inner))
            }

            /// Iterates over shared references to the elements.
            pub fn iter(&self) -> core::slice::Iter<'_, V> {
                use $crate::collections::linear::contiguous_data::QuantizedContiguousTrait;
                self.0.iter()
            }

            /// Iterates over mutable references to the elements.
            pub fn iter_mut(&mut self) -> core::slice::IterMut<'_, V> {
                use $crate::collections::linear::contiguous_data::QuantizedContiguousMutTrait;
                self.0.iter_mut()
            }

            /// Returns a shared reference to the element at `index`, without
            /// bounds checking.
            ///
            /// # Safety
            /// - `index` must be in bounds.
            pub unsafe fn get_par(&self, index: $index<Q>) -> &V {
                use $crate::collections::linear::contiguous_data::QuantizedContiguousParTrait;
                unsafe { self.0.get_par(index.const_deref()) }
            }

            /// Returns a mutable reference to the element at `index` through a
            /// shared `&self`, enabling parallel mutation of disjoint indices.
            ///
            /// # Safety
            /// - `index` must be in bounds.
            /// - Concurrent callers must only ever target disjoint indices.
            pub unsafe fn get_mut_par(&self, index: $index<Q>) -> &mut V {
                use $crate::collections::linear::contiguous_data::QuantizedContiguousParMutTrait;
                unsafe { self.0.get_mut_par(index.const_deref()) }
            }
        }

        impl<Q: $crate::values::quantizable::QuantizedIndexCountTrait, V: Clone + Copy, const N: usize>
            core::ops::Index<$index<Q>> for $struct_name<Q, V, N>
        {
            type Output = V;
            fn index(&self, index: $index<Q>) -> &V {
                &self.0[index.const_deref()]
            }
        }

        impl<Q: $crate::values::quantizable::QuantizedIndexCountTrait, V: Clone + Copy, const N: usize>
            core::ops::IndexMut<$index<Q>> for $struct_name<Q, V, N>
        {
            fn index_mut(&mut self, index: $index<Q>) -> &mut V {
                &mut self.0[index.const_deref()]
            }
        }

        impl<Q: $crate::values::quantizable::QuantizedIndexCountTrait, V: Clone + Copy, const N: usize>
            From<[V; N]> for $struct_name<Q, V, N>
        {
            fn from(value: [V; N]) -> Self {
                Self::from_array(value)
            }
        }
    };
}
