[package]
name = "feagi-io-basis"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "Shared Structs and Traits between feagi-correspondence-io subcrates"

[features]

std = [
    "alloc",
    "feagi-basis/std",
    "serde/std", "thingbuf/std",
]

alloc = [
    "feagi-basis/alloc",
    "serde/alloc", "thingbuf/alloc",
]

# Support contracts at all
contract_feagi_server_requests = []

[dependencies]


# Root Crates
feagi-basis = {path = "../../../feagi-basis"}

# External Crates
paste = {workspace = true}
serde = { workspace = true, features = ["derive"] }
thingbuf = {workspace = true, features = ["static"]}