[package]
name = "feagi-models"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "Contains the definitions and math behind the neuron and synapse models"

[dependencies]
feagi-data = {path = "../feagi-data" }

paste = {workspace = true}
enum_delegate = {workspace = true}
half = {workspace = true}

