[package]
name = "feagi-models"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "Contains the definitions and math behind the neuron and synapse models"

[features]

default = [
    "std",
]

std = [
    "alloc",
    "serde/std",
]

alloc = [
    "serde",
    "serde/alloc",
    "serde/derive",
]

[dependencies]
feagi-data = {path = "../feagi-data" }
feagi-genomic-context = {path = "../feagi-genomic-context" }

paste = {workspace = true}
half = {workspace = true}
serde = { workspace = true, optional = true }

