[package]
name = "feagi-correspondence"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "Root library for describing and executing communication between the feagi server and clients"

[features]

std = [
    "alloc",
    "feagi-basis/std", "feagi-correspondence-io/std",
    "serde/std", "serde_json/std",
]

alloc = [
    "feagi-basis/alloc", "feagi-correspondence-io/alloc",
    "serde/alloc", "serde/derive", "serde_json/alloc",
]

#serde_json = [
#    "dep:serde_json",
#    "feagi-basis/serde_json", "feagi-correspondence-io/serde_json"
#]

feagi-server-requests-rest = [
    #"serde_json", # required for serialization of data
    "feagi-correspondence-io/rest-server"
]

feagi-server-requests-rest-swagger = [
    "feagi-server-requests-rest",
    "feagi-correspondence-io/rest-server-swagger"
]

# Platform targets

[dependencies]
# Sub Crates
#feagi-correspondence-serialization = {path = "feagi-correspondence-serialization"}
feagi-correspondence-io = {path = "feagi-correspondence-io"}

# Root Crates
feagi-basis = {path = "../feagi-basis"}

# External crates
paste = {workspace = true}
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = [] } # TODO make optional again
byteorder = {workspace = true}
base64 = {workspace = true}
ndarray = {workspace = true}
rayon = {workspace = true}
image = {workspace = true}
getrandom = "0.2.17" # TODO delete me!