[package]
name = "feagi-correspondence"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "Root library for describing and executing communication between the feagi server and clients"

[features]

default = [
    "std",

    "serde_json"
]

std = [
    "alloc",
    "feagi-correspondence-io/std",
    "serde/std", "serde_json/std",
]

alloc = [
    "serde/alloc", "serde/derive", "serde_json/alloc",
]

serde_json = [
    "dep:serde_json"
]


feagi-server-requests-rest = [
    "serde_json"
]

# Platform targets

[dependencies]
# Sub Crates
#feagi-correspondence-serialization = {path = "feagi-correspondence-serialization"}
feagi-correspondence-io = {path = "feagi-correspondence-io"}


# Root Crates
feagi-basis = {path = "../feagi-basis"}

# External crates
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, optional = true, features = [] }