[package]
name = "feagi-correspondence"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "Root library for describing and executing communication between the feagi server and clients"

[features]

default = [
    "std",
]

std = [
    "alloc",
    "serde/std", "serde_json/std",
]

alloc = [
    "serde_json",
    "serde/alloc", "serde/derive", "serde_json/alloc",
]

# Platform targets

[dependencies]
# Sub Crates
feagi-correspondence-serialization = {path = "feagi-correspondence-serialization"}
feagi-correspondence-io = {path = "feagi-correspondence-io"}
feagi-correspondence-contracts = {path = "feagi-correspondence-contracts"}

# Root Crates
feagi-basis = {path = "../feagi-basis"}

# External crates
serde = { workspace = true }
serde_json = { workspace = true, optional = true }