[package]
name = "feagi-runtimes"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "Root library for holding common patterns of feagi runtimes / executables"

[features]



[dependencies]

# FEAGI Root Crates
feagi-basis = {path = "../feagi-basis"}
feagi-brain = {path = "../feagi-brain"}



[lints]
workspace = true
