[package]
name = "feagi-runtimes"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "Root library for holding common patterns of feagi runtimes / executables"

[features]

std = [
    "alloc",
    "thiserror/std", "serde/std", "serde_json/std", "ahash/std", "thingbuf/std",
]

alloc = [
    "serde/alloc", "serde_json/alloc", "thingbuf/alloc", "heapless/alloc",
]

[dependencies]

# FEAGI Root Crates
feagi-basis = {path = "../feagi-basis"}
feagi-transport = {path = "../feagi-transport"}

# External Crates
thiserror = {workspace = true}
paste = { workspace = true }
ahash = { workspace = true, features = ["serde"]}
serde = { workspace = true, features = ["derive"]}
serde_json = { workspace = true, optional = true}
thingbuf = {workspace = true, features = ["static"]} # TODO review features
heapless = {workspace = true}

[lints]
workspace = true
