use feagi_data::{create_quantized_decimal_wrapper, create_quantized_index_count_wrapper, create_quantized_spatial_index_coordinate_3d_wrapper, create_quantized_spatial_index_dimensions_3d_wrapper};

/// We may use different Quantizations in various places
create_quantized_decimal_wrapper!(NeuronVoxelPotentialGeneric);
create_quantized_index_count_wrapper!(NeuronVoxelAxisGeneric);
create_quantized_index_count_wrapper!(NeuronVoxelLinearIndexGeneric);
create_quantized_spatial_index_coordinate_3d_wrapper!(NeuronVoxelCoordinateGeneric, NeuronVoxelAxisGeneric, NeuronVoxelAxisGeneric, NeuronVoxelAxisGeneric);
create_quantized_spatial_index_dimensions_3d_wrapper!(NeuronVoxelDimensionsGeneric, NeuronVoxelCoordinateGeneric, NeuronVoxelLinearIndexGeneric, NeuronVoxelAxisGeneric, NeuronVoxelAxisGeneric, NeuronVoxelAxisGeneric);


