mod percentage_1d_linear;
mod percentage_2d_linear;
mod percentage_3d_linear;
mod percentage_4d_linear;
mod signed_percentage_1d_linear;
mod signed_percentage_2d_linear;
mod signed_percentage_3d_linear;
mod signed_percentage_4d_linear;

pub(crate) use percentage_1d_linear::PercentageLinearNeuronVoxelXYZPDecoder;
pub(crate) use percentage_2d_linear::Percentage2DLinearNeuronVoxelXYZPDecoder;
pub(crate) use percentage_3d_linear::Percentage3DLinearNeuronVoxelXYZPDecoder;
pub(crate) use percentage_4d_linear::Percentage4DLinearNeuronVoxelXYZPDecoder;
pub(crate) use signed_percentage_1d_linear::SignedPercentageLinearNeuronVoxelXYZPDecoder;
pub(crate) use signed_percentage_2d_linear::SignedPercentage2DLinearNeuronVoxelXYZPDecoder;
pub(crate) use signed_percentage_3d_linear::SignedPercentage3DLinearNeuronVoxelXYZPDecoder;
pub(crate) use signed_percentage_4d_linear::SignedPercentage4DLinearNeuronVoxelXYZPDecoder;