[package]
name = "feagi-npu-engines"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true

[dependencies]
feagi-data = {path = "../../feagi-data"}
feagi-npu-common = {path = "../feagi-npu-common"}