[package]
name = "feagi-data-basis"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "Common shared data type, notably quantization levels"

[features]
std = [
    "alloc",
    "serde/std", "half/std"
]

alloc = [
    "serde/alloc", "half/alloc"
]

[dependencies]
# Root Crates
feagi-basis = {path = "../../feagi-basis"}

# External Crates
serde = {workspace = true, default-features = false, features = ["derive"]}
half = {workspace = true, default-features = false, features = ["serde"]}
